#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# run_chipagent_dut.bash
# DV Skills GUI — DUT Configuration section
#
# Environment variables injected by the GUI backend:
#   TOP_MODULE   CLOCK_FREQ   TIMESCALE   RESET_POLARITY
#   WORKSPACE_DIR   PROJECT_NAME
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

TOP_MODULE="${TOP_MODULE:-}"
CLOCK_FREQ="${CLOCK_FREQ:-}"
TIMESCALE="${TIMESCALE:-1ns/1ps}"
RESET_POLARITY="${RESET_POLARITY:-active_low}"
WORKSPACE_DIR="${WORKSPACE_DIR:-}"
PROJECT_NAME="${PROJECT_NAME:-project}"

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  ChipAgent — DUT Configuration"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Top module    : ${TOP_MODULE:-(not set)}"
echo "  Clock freq    : ${CLOCK_FREQ:-(not set)} MHz"
echo "  Timescale     : ${TIMESCALE}"
echo "  Reset polarity: ${RESET_POLARITY}"
echo ""

if [[ -z "$TOP_MODULE" ]]; then
  echo "ERROR: TOP_MODULE is not set." >&2; exit 1
fi
if [[ -z "$CLOCK_FREQ" ]]; then
  echo "ERROR: CLOCK_FREQ is not set." >&2; exit 1
fi

# ── Derived values ────────────────────────────────────────────────────────────
PERIOD=$(python3 -c "print(f'{1000/${CLOCK_FREQ}:.3f}')" 2>/dev/null || \
         awk "BEGIN{printf \"%.3f\", 1000/${CLOCK_FREQ}}")
HALF=$(python3 -c "print(f'{500/${CLOCK_FREQ}:.3f}')" 2>/dev/null || \
       awk "BEGIN{printf \"%.3f\", 500/${CLOCK_FREQ}}")

case "${RESET_POLARITY,,}" in
  active_low)  RST_ACTIVE=0; RST_DEASSERT=1; RST_EDGE="negedge" ;;
  active_high) RST_ACTIVE=1; RST_DEASSERT=0; RST_EDGE="posedge"  ;;
  *)           RST_ACTIVE=0; RST_DEASSERT=1; RST_EDGE="negedge" ;;
esac

echo "  Clock period  : ${PERIOD} ns"
echo "  Half period   : ${HALF} ns"
echo "  Reset active  : ${RST_ACTIVE} (${RST_EDGE})"
echo ""

# ── Output directory ──────────────────────────────────────────────────────────
if [[ -n "$WORKSPACE_DIR" ]]; then
  OUTDIR="${WORKSPACE_DIR}/${PROJECT_NAME}/dv/tb"
else
  OUTDIR="./dv/tb"
fi
mkdir -p "${OUTDIR}"
echo "  Output dir    : ${OUTDIR}"
echo ""

# ── dut_config.yaml ───────────────────────────────────────────────────────────
cat > "${OUTDIR}/dut_config.yaml" <<YAML
# DUT Configuration — generated by run_chipagent_dut.bash
top_module:    "${TOP_MODULE}"
clock_freq_mhz: ${CLOCK_FREQ}
clock_period_ns: ${PERIOD}
timescale:     "${TIMESCALE}"
reset_polarity: "${RESET_POLARITY}"
reset_active:   ${RST_ACTIVE}
reset_deassert: ${RST_DEASSERT}
generated_at:  "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
YAML
echo "  dut_config.yaml       written"

# ── dut_params_pkg.sv ─────────────────────────────────────────────────────────
cat > "${OUTDIR}/dut_params_pkg.sv" <<SV
// dut_params_pkg.sv — DUT parameter package
// Generated by run_chipagent_dut.bash
// DO NOT EDIT — regenerate via DV Skills GUI > DUT Configuration

\`timescale ${TIMESCALE}

package dut_params_pkg;

  // ── Clock ─────────────────────────────────────────────────────────────────
  parameter real CLK_FREQ_MHZ   = ${CLOCK_FREQ};
  parameter real CLK_PERIOD_NS  = ${PERIOD};
  parameter real CLK_HALF_NS    = ${HALF};

  // ── Reset ─────────────────────────────────────────────────────────────────
  parameter logic RST_ACTIVE    = 1'b${RST_ACTIVE};
  parameter logic RST_DEASSERT  = 1'b${RST_DEASSERT};
  parameter int   RST_CYCLES    = 10;

  // ── Top-level module name ─────────────────────────────────────────────────
  parameter string DUT_TOP      = "${TOP_MODULE}";

endpackage : dut_params_pkg
SV
echo "  dut_params_pkg.sv     written"

# ── dut_clk_rst_if.sv ─────────────────────────────────────────────────────────
cat > "${OUTDIR}/dut_clk_rst_if.sv" <<SV
// dut_clk_rst_if.sv — Clock / Reset interface
// Generated by run_chipagent_dut.bash
\`timescale ${TIMESCALE}
import dut_params_pkg::*;

interface dut_clk_rst_if;
  logic clk;
  logic rst_n;

  // ── Clock generation ──────────────────────────────────────────────────────
  initial clk = 1'b0;
  always #(CLK_HALF_NS) clk = ~clk;

  // ── Reset task ────────────────────────────────────────────────────────────
  task automatic apply_reset(int cycles = RST_CYCLES);
    rst_n = RST_ACTIVE;
    repeat (cycles) @(${RST_EDGE} clk);
    rst_n = RST_DEASSERT;
    @(${RST_EDGE} clk);
  endtask

  // ── Clocking block ────────────────────────────────────────────────────────
  clocking driver_cb @(posedge clk);
    default input #1step output #1;
  endclocking

endinterface : dut_clk_rst_if
SV
echo "  dut_clk_rst_if.sv     written"

echo ""
echo "✓  DUT configuration generated for '${TOP_MODULE}'"
