#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# run_chipagent_sim.bash
# DV Skills GUI — Simulation Defaults section
#
# Environment variables injected by the GUI backend:
#   WAVE_FORMAT   UVM_VERBOSITY   EXTRA_SIM_FLAGS
#   EDA_TOOL   EDA_TOOL_PATH   WORKSPACE_DIR   PROJECT_NAME
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

WAVE_FORMAT="${WAVE_FORMAT:-fsdb}"
UVM_VERBOSITY="${UVM_VERBOSITY:-UVM_MEDIUM}"
EXTRA_SIM_FLAGS="${EXTRA_SIM_FLAGS:-}"
EDA_TOOL="${EDA_TOOL:-vcs}"
EDA_TOOL_PATH="${EDA_TOOL_PATH:-}"
WORKSPACE_DIR="${WORKSPACE_DIR:-}"
PROJECT_NAME="${PROJECT_NAME:-project}"

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  ChipAgent — Simulation Defaults"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Wave format   : ${WAVE_FORMAT}"
echo "  UVM verbosity : ${UVM_VERBOSITY}"
echo "  Extra flags   : ${EXTRA_SIM_FLAGS:-(none)}"
echo "  EDA tool      : ${EDA_TOOL}"
echo ""

# ── Wave dump flags ───────────────────────────────────────────────────────────
case "${WAVE_FORMAT,,}" in
  fsdb)
    WAVE_FLAGS="-debug_access+all +fsdb+delta=on +fsdb+mda=on"
    WAVE_OPEN_CMD="verdi -ssf waves.fsdb &"
    ;;
  vpd)
    WAVE_FLAGS="-debug_access+all +vpdfile+waves.vpd"
    WAVE_OPEN_CMD="dve -vpd waves.vpd &"
    ;;
  vcd)
    WAVE_FLAGS="+dumpvars"
    WAVE_OPEN_CMD="gtkwave waves.vcd &"
    ;;
  none)
    WAVE_FLAGS=""
    WAVE_OPEN_CMD="# No waves configured"
    ;;
esac

# ── Output directory ──────────────────────────────────────────────────────────
if [[ -n "$WORKSPACE_DIR" ]]; then
  OUTDIR="${WORKSPACE_DIR}/${PROJECT_NAME}/dv/scripts"
else
  OUTDIR="./dv/scripts"
fi
mkdir -p "${OUTDIR}"
echo "  Output dir    : ${OUTDIR}"
echo ""

# ── sim_defaults.yaml ─────────────────────────────────────────────────────────
cat > "${OUTDIR}/sim_defaults.yaml" <<YAML
# sim_defaults.yaml — generated by run_chipagent_sim.bash
wave_format:     "${WAVE_FORMAT}"
uvm_verbosity:   "${UVM_VERBOSITY}"
extra_sim_flags: "${EXTRA_SIM_FLAGS}"
eda_tool:        "${EDA_TOOL}"
eda_tool_path:   "${EDA_TOOL_PATH}"
generated_at:    "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
YAML
echo "  sim_defaults.yaml     written"

# ── Makefile.sim_defaults ─────────────────────────────────────────────────────
cat > "${OUTDIR}/Makefile.sim_defaults" <<MAKEFILE
# Makefile.sim_defaults — include in your top-level Makefile
# Generated by run_chipagent_sim.bash

EDA_TOOL       ?= ${EDA_TOOL}
EDA_TOOL_PATH  ?= ${EDA_TOOL_PATH}
UVM_VERBOSITY  ?= ${UVM_VERBOSITY}
WAVE_FLAGS     ?= ${WAVE_FLAGS}
EXTRA_FLAGS    ?= ${EXTRA_SIM_FLAGS}

SIM_FLAGS      += +UVM_VERBOSITY=\$(UVM_VERBOSITY)
SIM_FLAGS      += \$(WAVE_FLAGS)
SIM_FLAGS      += \$(EXTRA_FLAGS)
MAKEFILE
echo "  Makefile.sim_defaults written"

# ── run_sim.sh template ───────────────────────────────────────────────────────
cat > "${OUTDIR}/run_sim.sh" <<RUNSH
#!/usr/bin/env bash
# run_sim.sh — simulation runner template
# Generated by run_chipagent_sim.bash
set -euo pipefail

TOOL="${EDA_TOOL}"
TOOL_PATH="${EDA_TOOL_PATH}"
UVM_VERBOSITY="${UVM_VERBOSITY}"
WAVE_FORMAT="${WAVE_FORMAT}"
EXTRA_FLAGS="${EXTRA_SIM_FLAGS}"
TEST="\${1:-base_test}"
SEED="\${2:-\$RANDOM}"

echo "Running test: \${TEST}  seed: \${SEED}"

case "\${TOOL,,}" in
  vcs)
    \${TOOL_PATH}/bin/simv -full64 \\
      +UVM_TESTNAME=\${TEST} \\
      +ntb_random_seed=\${SEED} \\
      +UVM_VERBOSITY=\${UVM_VERBOSITY} \\
      ${WAVE_FLAGS} \\
      \${EXTRA_FLAGS}
    ;;
  questa)
    \${TOOL_PATH}/bin/vsim -c -do "run -all; quit" \\
      -sv_seed \${SEED} \\
      +UVM_TESTNAME=\${TEST} \\
      +UVM_VERBOSITY=\${UVM_VERBOSITY} \\
      \${EXTRA_FLAGS}
    ;;
  xcelium)
    \${TOOL_PATH}/bin/xrun \\
      +UVM_TESTNAME=\${TEST} \\
      -seed \${SEED} \\
      +UVM_VERBOSITY=\${UVM_VERBOSITY} \\
      \${EXTRA_FLAGS}
    ;;
esac

# Open waveform
# ${WAVE_OPEN_CMD}
RUNSH
chmod +x "${OUTDIR}/run_sim.sh"
echo "  run_sim.sh            written (executable)"

echo ""
echo "✓  Simulation defaults applied and written to ${OUTDIR}"
