#!/usr/bin/env python3
"""
generate_env_setup.py — S4 DV Environment Setup Generator

Reads a dv_env_config.json and generates the complete DV project environment:
  - Directory scaffold
  - Environment files: proj.cshrc, proj.bashrc, .env
  - VCS simulation files: Makefile, synopsys_sim.setup, compile.f, rtl.f,
                          waves.tcl, regression.sh
  - UVM TB skeleton files (10 files)
  - dv_env_data.json output for S5+

Usage:
    python3 generate_env_setup.py --config /tmp/<proj>_env_config.json
    python3 generate_env_setup.py --config /tmp/<proj>_env_config.json --overwrite
"""

import json
import os
import sys
import stat
import argparse
from pathlib import Path
from datetime import date as _date


# ─── Helpers ──────────────────────────────────────────────────────────────────

def load_config(path):
    with open(path) as f:
        return json.load(f)


def mkdir(path):
    Path(path).mkdir(parents=True, exist_ok=True)


def write_file(path, content, overwrite=False):
    p = Path(path)
    if p.exists() and not overwrite:
        print(f"  [SKIP]  {p}  (exists — use --overwrite to replace)")
        return False
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(content)
    print(f"  [GEN]   {p}")
    return True


TODAY = str(_date.today())


# ─── Environment files ────────────────────────────────────────────────────────

def gen_cshrc(cfg, proj_root):
    p       = cfg["project_name"]
    vcs     = cfg.get("vcs_home",       "<VCS_HOME>")
    verdi   = cfg.get("verdi_home",     "<VERDI_HOME>")
    uvm     = cfg.get("uvm_home",       "<UVM_HOME>")
    uver    = cfg.get("uvm_version",    "1.2")
    lic     = cfg.get("license_server", "<LICENSE_SERVER>")
    pr      = str(proj_root)
    return (
        "#!/bin/csh\n"
        "##############################################################################\n"
        f"# proj.cshrc — {p} DV Project Environment (C Shell)\n"
        f"# Generated by dv-env-setup (S4)   Date: {TODAY}\n"
        "# Source with:  source proj.cshrc\n"
        "##############################################################################\n\n"
        "# ── Project paths ────────────────────────────────────────────────────────────\n"
        f"setenv PROJECT_ROOT    {pr}\n"
        f"setenv PROJECT_NAME    {p}\n"
        "setenv DV_ROOT         ${PROJECT_ROOT}/dv\n"
        "setenv RTL_ROOT        ${PROJECT_ROOT}/rtl\n"
        "setenv SIM_ROOT        ${DV_ROOT}/sim\n"
        "setenv TB_ROOT         ${DV_ROOT}/tb\n"
        "setenv ENV_ROOT        ${DV_ROOT}/env\n"
        "setenv SEQ_ROOT        ${DV_ROOT}/seq_lib\n"
        "setenv AGENTS_ROOT     ${DV_ROOT}/agents\n"
        "setenv SCRIPTS_ROOT    ${DV_ROOT}/scripts\n"
        "setenv COV_ROOT        ${DV_ROOT}/cov\n\n"
        "# ── Tool paths ───────────────────────────────────────────────────────────────\n"
        f"setenv VCS_HOME        {vcs}\n"
        f"setenv VERDI_HOME      {verdi}\n"
        f"setenv UVM_HOME        {uvm}\n"
        f"setenv UVM_VERSION     {uver}\n\n"
        "# ── License ──────────────────────────────────────────────────────────────────\n"
        f"setenv SYNOPSYS_LICENSE_FILE  {lic}\n"
        "setenv VCS_ARCH_OVERRIDE       linux\n"
        "setenv VCS_LIC_EXPIRE_WARNING  0\n\n"
        "# ── PATH setup ───────────────────────────────────────────────────────────────\n"
        "setenv PATH            ${VCS_HOME}/bin:${VERDI_HOME}/bin:${PATH}\n"
        "setenv LD_LIBRARY_PATH ${VCS_HOME}/lib:${VERDI_HOME}/lib:${LD_LIBRARY_PATH}\n\n"
        "# ── Verdi FSDB library ───────────────────────────────────────────────────────\n"
        "setenv NOVAS_HOME      ${VERDI_HOME}\n"
        "setenv SYNOPSYS        ${VCS_HOME}\n\n"
        "# ── Useful aliases ───────────────────────────────────────────────────────────\n"
        "alias cdproj    'cd ${PROJECT_ROOT}'\n"
        "alias cddv      'cd ${DV_ROOT}'\n"
        "alias cdsim     'cd ${SIM_ROOT}'\n"
        "alias cdrtl     'cd ${RTL_ROOT}'\n"
        "alias cdtb      'cd ${TB_ROOT}'\n"
        "alias mk        'make -C ${SIM_ROOT}'\n"
        "alias mkclean   'make -C ${SIM_ROOT} clean'\n"
        "alias mksim     'make -C ${SIM_ROOT} sim'\n"
        "alias mkcompile 'make -C ${SIM_ROOT} compile'\n"
        "alias mkhelp    'make -C ${SIM_ROOT} help'\n\n"
        f"echo '>> {p} DV environment loaded (csh)'\n"
        "echo '>> PROJECT_ROOT =' ${PROJECT_ROOT}\n"
        "echo '>> VCS_HOME     =' ${VCS_HOME}\n"
        "echo '>> VERDI_HOME   =' ${VERDI_HOME}\n"
        "echo '>> UVM_HOME     =' ${UVM_HOME}\n"
    )


def gen_bashrc(cfg, proj_root):
    p       = cfg["project_name"]
    vcs     = cfg.get("vcs_home",       "<VCS_HOME>")
    verdi   = cfg.get("verdi_home",     "<VERDI_HOME>")
    uvm     = cfg.get("uvm_home",       "<UVM_HOME>")
    uver    = cfg.get("uvm_version",    "1.2")
    lic     = cfg.get("license_server", "<LICENSE_SERVER>")
    pr      = str(proj_root)
    return (
        "#!/bin/bash\n"
        "##############################################################################\n"
        f"# proj.bashrc — {p} DV Project Environment (Bash)\n"
        f"# Generated by dv-env-setup (S4)   Date: {TODAY}\n"
        "# Source with:  source proj.bashrc\n"
        "##############################################################################\n\n"
        "# ── Project paths ────────────────────────────────────────────────────────────\n"
        f'export PROJECT_ROOT="{pr}"\n'
        f'export PROJECT_NAME="{p}"\n'
        'export DV_ROOT="${PROJECT_ROOT}/dv"\n'
        'export RTL_ROOT="${PROJECT_ROOT}/rtl"\n'
        'export SIM_ROOT="${DV_ROOT}/sim"\n'
        'export TB_ROOT="${DV_ROOT}/tb"\n'
        'export ENV_ROOT="${DV_ROOT}/env"\n'
        'export SEQ_ROOT="${DV_ROOT}/seq_lib"\n'
        'export AGENTS_ROOT="${DV_ROOT}/agents"\n'
        'export SCRIPTS_ROOT="${DV_ROOT}/scripts"\n'
        'export COV_ROOT="${DV_ROOT}/cov"\n\n'
        "# ── Tool paths ───────────────────────────────────────────────────────────────\n"
        f'export VCS_HOME="{vcs}"\n'
        f'export VERDI_HOME="{verdi}"\n'
        f'export UVM_HOME="{uvm}"\n'
        f'export UVM_VERSION="{uver}"\n\n'
        "# ── License ──────────────────────────────────────────────────────────────────\n"
        f'export SYNOPSYS_LICENSE_FILE="{lic}"\n'
        'export VCS_ARCH_OVERRIDE="linux"\n'
        'export VCS_LIC_EXPIRE_WARNING=0\n\n'
        "# ── PATH setup ───────────────────────────────────────────────────────────────\n"
        'export PATH="${VCS_HOME}/bin:${VERDI_HOME}/bin:${PATH}"\n'
        'export LD_LIBRARY_PATH="${VCS_HOME}/lib:${VERDI_HOME}/lib:${LD_LIBRARY_PATH:-}"\n\n'
        "# ── Verdi FSDB library ───────────────────────────────────────────────────────\n"
        'export NOVAS_HOME="${VERDI_HOME}"\n'
        'export SYNOPSYS="${VCS_HOME}"\n\n'
        "# ── Useful aliases ───────────────────────────────────────────────────────────\n"
        'alias cdproj="cd ${PROJECT_ROOT}"\n'
        'alias cddv="cd ${DV_ROOT}"\n'
        'alias cdsim="cd ${SIM_ROOT}"\n'
        'alias cdrtl="cd ${RTL_ROOT}"\n'
        'alias cdtb="cd ${TB_ROOT}"\n'
        'alias mk="make -C ${SIM_ROOT}"\n'
        'alias mkclean="make -C ${SIM_ROOT} clean"\n'
        'alias mksim="make -C ${SIM_ROOT} sim"\n'
        'alias mkcompile="make -C ${SIM_ROOT} compile"\n'
        'alias mkhelp="make -C ${SIM_ROOT} help"\n\n'
        f'echo ">> {p} DV environment loaded (bash)"\n'
        'echo ">> PROJECT_ROOT = ${PROJECT_ROOT}"\n'
        'echo ">> VCS_HOME     = ${VCS_HOME}"\n'
        'echo ">> VERDI_HOME   = ${VERDI_HOME}"\n'
        'echo ">> UVM_HOME     = ${UVM_HOME}"\n'
    )


def gen_dotenv(cfg, proj_root):
    p       = cfg["project_name"]
    vcs     = cfg.get("vcs_home",       "<VCS_HOME>")
    verdi   = cfg.get("verdi_home",     "<VERDI_HOME>")
    uvm     = cfg.get("uvm_home",       "<UVM_HOME>")
    uver    = cfg.get("uvm_version",    "1.2")
    lic     = cfg.get("license_server", "<LICENSE_SERVER>")
    pr      = str(proj_root)
    return (
        f"# .env — {p} DV Project Environment Variables\n"
        f"# Generated by dv-env-setup (S4)   Date: {TODAY}\n"
        "# Compatible with docker --env-file, direnv, and python-dotenv\n\n"
        f"PROJECT_ROOT={pr}\n"
        f"PROJECT_NAME={p}\n"
        f"DV_ROOT={pr}/dv\n"
        f"RTL_ROOT={pr}/rtl\n"
        f"SIM_ROOT={pr}/dv/sim\n"
        f"VCS_HOME={vcs}\n"
        f"VERDI_HOME={verdi}\n"
        f"UVM_HOME={uvm}\n"
        f"UVM_VERSION={uver}\n"
        f"SYNOPSYS_LICENSE_FILE={lic}\n"
        "VCS_ARCH_OVERRIDE=linux\n"
    )


# ─── VCS simulation files ─────────────────────────────────────────────────────

def gen_synopsys_sim_setup(cfg):
    p = cfg["project_name"]
    return (
        f"# synopsys_sim.setup — VCS Library Configuration\n"
        f"# Generated by dv-env-setup (S4)   Date: {TODAY}\n"
        "# Place in the simulation run directory (dv/sim/) or pointed to via VCS_SYNOPSYS_SETUP\n\n"
        "# Work library — all compiled units go here by default\n"
        "WORK > DEFAULT\n"
        "DEFAULT : ./build/AN.DB\n\n"
        "# Simulation resolution\n"
        "TIMEUNIT      = 1ns\n"
        "TIMEPRECISION = 1ps\n\n"
        "# ── Library mappings ──────────────────────────────────────────────────────────\n"
        "# Add third-party IP library mappings below:\n"
        "# <lib_name> : <absolute_path_to_lib>\n\n"
        "# UVM is auto-compiled by VCS with -ntb_opts uvm-X.Y — no mapping needed.\n"
        "# FSDB/Verdi: auto-loaded via VERDI_HOME/NOVAS_HOME environment variables.\n"
    )


def gen_compile_f(cfg, proj_root):
    p    = cfg["project_name"]
    pr   = str(proj_root)
    uvm  = cfg.get("uvm_home", "${UVM_HOME}")
    return (
        f"// compile.f — Testbench Compilation File List\n"
        f"// Generated by dv-env-setup (S4)   Date: {TODAY}\n"
        "// Passed to vlogan for the TB compile pass (make compile_tb)\n"
        "// RTL files are in rtl.f — compiled separately via make compile_rtl\n\n"
        "//----------------------------------------------------------------------\n"
        "// UVM library\n"
        "//----------------------------------------------------------------------\n"
        f"+incdir+{uvm}/src\n"
        f"{uvm}/src/uvm_pkg.sv\n\n"
        "//----------------------------------------------------------------------\n"
        "// DV environment package (must be compiled first)\n"
        "//----------------------------------------------------------------------\n"
        f"+incdir+{pr}/dv/env\n"
        f"{pr}/dv/env/{p}_env_pkg.sv\n\n"
        "//----------------------------------------------------------------------\n"
        "// TB include directories\n"
        "//----------------------------------------------------------------------\n"
        f"+incdir+{pr}/dv/tb\n"
        f"+incdir+{pr}/dv/env\n"
        f"+incdir+{pr}/dv/seq_lib\n"
        f"+incdir+{pr}/dv/agents\n\n"
        "//----------------------------------------------------------------------\n"
        "// Interfaces and TB top\n"
        "//----------------------------------------------------------------------\n"
        f"{pr}/dv/tb/{p}_if.sv\n"
        f"{pr}/dv/tb/{p}_tb_top.sv\n\n"
        "//----------------------------------------------------------------------\n"
        "// Environment components\n"
        "//----------------------------------------------------------------------\n"
        f"{pr}/dv/env/{p}_env_cfg.sv\n"
        f"{pr}/dv/env/{p}_scoreboard.sv\n"
        f"{pr}/dv/env/{p}_coverage.sv\n"
        f"{pr}/dv/env/{p}_env.sv\n\n"
        "//----------------------------------------------------------------------\n"
        "// Sequences and tests\n"
        "//----------------------------------------------------------------------\n"
        f"{pr}/dv/seq_lib/{p}_base_seq.sv\n"
        f"{pr}/dv/seq_lib/{p}_base_test.sv\n"
        f"{pr}/dv/seq_lib/{p}_sanity_test.sv\n\n"
        "//----------------------------------------------------------------------\n"
        "// Agents (uncomment and add agent compile.f files as agents are developed)\n"
        "//----------------------------------------------------------------------\n"
        "// -f ${AGENTS_ROOT}/<agent_name>/compile.f\n"
    )


def gen_rtl_f(cfg, proj_root):
    p         = cfg["project_name"]
    pr        = str(proj_root)
    rtl_files = cfg.get("rtl_files", [])
    if rtl_files:
        file_lines = "\n".join(f"{pr}/rtl/{f}" for f in rtl_files)
    else:
        file_lines = "// TODO: Add RTL source files in compilation order (packages first)\n// ${RTL_ROOT}/<module>.sv"
    return (
        f"// rtl.f — RTL Compilation File List\n"
        f"// Generated by dv-env-setup (S4)   Date: {TODAY}\n"
        "// Passed to vlogan for the RTL compile pass (make compile_rtl)\n\n"
        "//----------------------------------------------------------------------\n"
        "// RTL include directories\n"
        "//----------------------------------------------------------------------\n"
        f"+incdir+{pr}/rtl\n\n"
        "//----------------------------------------------------------------------\n"
        "// RTL source files — add in compilation order (packages before modules)\n"
        "//----------------------------------------------------------------------\n"
        f"{file_lines}\n"
    )


def gen_waves_tcl(cfg, proj_root):
    p  = cfg["project_name"]
    pr = str(proj_root)
    scope = cfg.get("wave_scope", f"{p}_tb_top")
    return (
        f"# waves.tcl — Verdi Waveform Configuration\n"
        f"# Generated by dv-env-setup (S4)   Date: {TODAY}\n"
        "# Used by VCS UCLi: make sim WAVES=1 passes -ucli -do waves.tcl\n\n"
        "# ── FSDB output file ──────────────────────────────────────────────────────────\n"
        "if {[info exists env(RUN_DIR)]} {\n"
        f"    set fsdb_path \"$env(RUN_DIR)/{p}.fsdb\"\n"
        "} else {\n"
        f"    set fsdb_path \"./{p}.fsdb\"\n"
        "}\n\n"
        "# ── Enable FSDB dump ─────────────────────────────────────────────────────────\n"
        "global vc_dbtype\n"
        "set vc_dbtype fsdb\n\n"
        f"fsdbDumpfile  $fsdb_path\n"
        f"fsdbDumpvars  0 {scope}\n"
        f"fsdbDumpSVA   0 {scope}\n\n"
        "# Dump memory arrays (comment out if FSDB becomes too large)\n"
        f"# fsdbDumpMDA 0 {scope}\n\n"
        "# ── Optional: limit dump to specific scopes ────────────────────────────────\n"
        f"# fsdbDumpvars 0 {scope}.u_dut     ;# DUT only\n"
        f"# fsdbDumpvars 0 {scope}.u_env     ;# ENV only\n\n"
        "# ── Start simulation ─────────────────────────────────────────────────────────\n"
        "run 0\n\n"
        "# ── Open waveform after simulation ────────────────────────────────────────────\n"
        "# To open in Verdi:\n"
        "#   make verdi TEST=<test> SEED=<seed>\n"
        "#   OR: $VERDI_HOME/bin/verdi -ssf <fsdb_path>\n"
    )


def gen_makefile(cfg, proj_root):
    p      = cfg["project_name"]
    vcs    = cfg.get("vcs_home",          "<VCS_HOME>")
    verdi  = cfg.get("verdi_home",        "<VERDI_HOME>")
    uvm    = cfg.get("uvm_home",          "<UVM_HOME>")
    uver   = cfg.get("uvm_version",       "1.2")
    ts     = cfg.get("timescale",         "1ns/1ps")
    tout   = cfg.get("default_timeout",   "1ms")
    cvtypes= cfg.get("coverage_types",    "line+cond+branch+tgl+fsm")
    ecf    = cfg.get("extra_compile_flags","")
    esf    = cfg.get("extra_sim_flags",   "")
    pr     = str(proj_root)

    # Tab character — critical for Makefile
    T = "\t"

    lines = [
        "##############################################################################",
        f"# Makefile — {p} DV Simulation",
        f"# Generated by dv-env-setup (S4)   Date: {TODAY}",
        "# Tool: Synopsys VCS + Verdi",
        "#",
        "# Run 'make help' for all targets and options.",
        "##############################################################################",
        "",
        "#------------------------------------------------------------------------------",
        "# Project paths",
        "#------------------------------------------------------------------------------",
        f"PROJECT    := {p}",
        "SIM_ROOT   := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))",
        f"PROJ_ROOT  := {pr}",
        "RTL_ROOT   ?= $(PROJ_ROOT)/rtl",
        "DV_ROOT    := $(PROJ_ROOT)/dv",
        "",
        "#------------------------------------------------------------------------------",
        "# Build and run directories",
        "#   BUILD_DIR : shared across ALL tests — compile once, run many",
        "#   RUN_DIR   : per-test run directory (testname_seed/)",
        "#   COV_DIR   : per-test coverage VDB",
        "#------------------------------------------------------------------------------",
        "BUILD_DIR  ?= $(SIM_ROOT)/build",
        "RUN_BASE   ?= $(SIM_ROOT)/run",
        "COV_BASE   ?= $(SIM_ROOT)/cov",
        "LOG_DIR    ?= $(SIM_ROOT)/logs",
        "",
        "#------------------------------------------------------------------------------",
        "# Test configuration",
        "#------------------------------------------------------------------------------",
        "TEST       ?= sanity",
        "SEED       ?= 1",
        "RUN_DIR    := $(RUN_BASE)/$(TEST)_$(SEED)",
        "COV_DIR    := $(COV_BASE)/$(TEST)_$(SEED).vdb",
        "",
        "#------------------------------------------------------------------------------",
        "# Tool paths — override if set differently in your shell environment",
        "#------------------------------------------------------------------------------",
        f"VCS_HOME   ?= {vcs}",
        f"VERDI_HOME ?= {verdi}",
        f"UVM_HOME   ?= {uvm}",
        f"UVM_VER    ?= {uver}",
        "",
        "VCS        := $(VCS_HOME)/bin/vcs",
        "VLOGAN     := $(VCS_HOME)/bin/vlogan",
        "VERDI      := $(VERDI_HOME)/bin/verdi",
        "URG        := $(VCS_HOME)/bin/urg",
        "",
        "#------------------------------------------------------------------------------",
        "# Feature switches — all default to OFF except LOG",
        "#   Override on command line:  make sim WAVES=1 COV=1",
        "#------------------------------------------------------------------------------",
        "WAVES      ?= 0    # 0=off | 1=dump FSDB via waves.tcl",
        "COV        ?= 0    # 0=off | 1=collect " + cvtypes,
        "LOG        ?= 1    # 0=off | 1=write simv.log in RUN_DIR",
        "TCL        ?= $(SIM_ROOT)/waves.tcl",
        "",
        "#------------------------------------------------------------------------------",
        "# Simulation options — all overridable from command line",
        "#   PLUSARGS  : extra plusargs        e.g.  PLUSARGS='+arg1+arg2'",
        "#   VPLUSARGS : extra value-plusargs  e.g.  VPLUSARGS='+key1+val1 +key2+val2'",
        "#   DEFINES   : extra defines         e.g.  DEFINES='+define+ERR_INJ'",
        "#   SIM_OPTS  : extra simv options",
        "#   COMP_OPTS : extra compile options",
        "#------------------------------------------------------------------------------",
        "PLUSARGS   ?=",
        "VPLUSARGS  ?=",
        "DEFINES    ?=",
        "SIM_OPTS   ?=",
        "COMP_OPTS  ?=",
        f"VERBOSITY  ?= UVM_MEDIUM",
        f"TIMEOUT    ?= {tout}",
        f"TIMESCALE  ?= {ts}",
        "",
        "#------------------------------------------------------------------------------",
        "# UVM options (always applied at simulation time)",
        "#------------------------------------------------------------------------------",
        "UVM_OPTS   := +UVM_TESTNAME=$(TEST)          \\",
        "              +ntb_random_seed=$(SEED)        \\",
        "              +UVM_VERBOSITY=$(VERBOSITY)     \\",
        "              +UVM_TIMEOUT=$(TIMEOUT)",
        "",
        "#------------------------------------------------------------------------------",
        "# Standard compile flags",
        "#------------------------------------------------------------------------------",
        "VCS_COMMON_FLAGS := -full64 -sverilog -sv                    \\",
        "                    -timescale=$(TIMESCALE)                   \\",
        "                    -kdb -lca                                 \\",
        "                    +incdir+$(UVM_HOME)/src                   \\",
        "                    -ntb_opts uvm-$(UVM_VER)                  \\",
    ]
    if ecf:
        lines.append(f"                    {ecf}                      \\")
    lines += [
        "                    $(COMP_OPTS)",
        "",
        "VLOGAN_RTL_FLAGS  := $(VCS_COMMON_FLAGS) $(DEFINES) -f $(SIM_ROOT)/rtl.f",
        "VLOGAN_TB_FLAGS   := $(VCS_COMMON_FLAGS) $(DEFINES) -f $(SIM_ROOT)/compile.f",
        "",
        "ELAB_FLAGS        := -full64 -kdb -lca                      \\",
        "                     -o $(BUILD_DIR)/simv                    \\",
        "                     -Mdir=$(BUILD_DIR)/csrc                 \\",
        "                     -debug_access+all",
        "",
        "#------------------------------------------------------------------------------",
        "# Waveform flags (added when WAVES=1)",
        "#------------------------------------------------------------------------------",
        "ifeq ($(WAVES),1)",
        "  WAVE_FLAGS  := -ucli -do $(TCL) +fsdb+delta +vcs+vcdpluson",
        "  WAVE_ELAB   := -debug_access+all",
        "else",
        "  WAVE_FLAGS  :=",
        "  WAVE_ELAB   :=",
        "endif",
        "",
        "#------------------------------------------------------------------------------",
        "# Coverage flags (added when COV=1)",
        "#------------------------------------------------------------------------------",
        "ifeq ($(COV),1)",
        f"  COV_ELAB_FLAGS := -cm {cvtypes} -cm_dir $(BUILD_DIR)/cm.vdb",
        f"  COV_SIM_FLAGS  := -cm {cvtypes} -cm_dir $(COV_DIR) -cm_name $(TEST)_$(SEED)",
        "else",
        "  COV_ELAB_FLAGS :=",
        "  COV_SIM_FLAGS  :=",
        "endif",
        "",
        "#------------------------------------------------------------------------------",
        "# Log flags (added when LOG=1)",
        "#------------------------------------------------------------------------------",
        "ifeq ($(LOG),1)",
        "  LOG_FLAGS := -l $(RUN_DIR)/simv.log",
        "else",
        "  LOG_FLAGS :=",
        "endif",
        "",
        "#------------------------------------------------------------------------------",
        "# Final simulation flags",
        "#------------------------------------------------------------------------------",
        "SIM_FLAGS  := $(UVM_OPTS)       \\",
        "              $(WAVE_FLAGS)     \\",
        "              $(COV_SIM_FLAGS)  \\",
        "              $(LOG_FLAGS)      \\",
        "              $(PLUSARGS)       \\",
        "              $(VPLUSARGS)      \\",
    ]
    if esf:
        lines.append(f"              {esf}            \\")
    lines += [
        "              $(SIM_OPTS)",
        "",
        "##############################################################################",
        "# TARGETS",
        "##############################################################################",
        "",
        ".PHONY: help show_config compile_rtl compile_tb elab compile \\",
        "        sim run regress cov_merge cov_report verdi           \\",
        "        clean_logs clean_run clean_cov clean_build clean",
        "",
        ".DEFAULT_GOAL := help",
        "",
        "#------------------------------------------------------------------------------",
        "# help — print all targets and options",
        "#------------------------------------------------------------------------------",
        "help:",
        T + '@printf "\\n"',
        T + f'@printf "╔══════════════════════════════════════════════════════════════╗\\n"',
        T + f'@printf "║  DV Simulation Makefile  ─  {p:<33}║\\n"',
        T + f'@printf "╠══════════════════════════════════════════════════════════════╣\\n"',
        T + f'@printf "║  COMPILATION TARGETS                                         ║\\n"',
        T + f'@printf "║    compile_rtl   Compile RTL files only (vlogan)             ║\\n"',
        T + f'@printf "║    compile_tb    Compile TB files (vlogan — needs RTL)       ║\\n"',
        T + f'@printf "║    elab          Elaborate all → $(BUILD_DIR)/simv           ║\\n"',
        T + f'@printf "║    compile       Full compile: RTL + TB + elab               ║\\n"',
        T + f'@printf "╠══════════════════════════════════════════════════════════════╣\\n"',
        T + f'@printf "║  SIMULATION TARGETS                                          ║\\n"',
        T + f'@printf "║    sim           Run test using existing shared simv         ║\\n"',
        T + f'@printf "║    run           compile + sim (first-time flow)             ║\\n"',
        T + f'@printf "╠══════════════════════════════════════════════════════════════╣\\n"',
        T + f'@printf "║  REGRESSION                                                  ║\\n"',
        T + f'@printf "║    regress       Run full regression via regression.sh       ║\\n"',
        T + f'@printf "╠══════════════════════════════════════════════════════════════╣\\n"',
        T + f'@printf "║  COVERAGE                                                    ║\\n"',
        T + f'@printf "║    cov_merge     Merge all .vdb files with urg               ║\\n"',
        T + f'@printf "║    cov_report    Open merged coverage in Verdi               ║\\n"',
        T + f'@printf "╠══════════════════════════════════════════════════════════════╣\\n"',
        T + f'@printf "║  WAVEFORM                                                    ║\\n"',
        T + f'@printf "║    verdi         Open Verdi with TEST/SEED waveform          ║\\n"',
        T + f'@printf "╠══════════════════════════════════════════════════════════════╣\\n"',
        T + f'@printf "║  CLEANUP                                                     ║\\n"',
        T + f'@printf "║    clean_logs    Remove .log files only                      ║\\n"',
        T + f'@printf "║    clean_run     Remove run/ directory                       ║\\n"',
        T + f'@printf "║    clean_cov     Remove cov/ directory                       ║\\n"',
        T + f'@printf "║    clean_build   Remove build/ (forces recompile)            ║\\n"',
        T + f'@printf "║    clean         Remove ALL generated directories            ║\\n"',
        T + f'@printf "╠══════════════════════════════════════════════════════════════╣\\n"',
        T + f'@printf "║  UTILITY                                                     ║\\n"',
        T + f'@printf "║    show_config   Print all current variable values           ║\\n"',
        T + f'@printf "╠══════════════════════════════════════════════════════════════╣\\n"',
        T + f'@printf "║  KEY OPTIONS (add after target name)                         ║\\n"',
        T + f'@printf "║    TEST=<name>         Test class name  (default: sanity)    ║\\n"',
        T + f'@printf "║    SEED=<N>            Random seed      (default: 1)         ║\\n"',
        T + f'@printf "║    WAVES=1             Enable FSDB waveform dump             ║\\n"',
        T + f'@printf "║    COV=1               Enable coverage collection            ║\\n"',
        T + f'@printf "║    LOG=0               Disable log file generation           ║\\n"',
        T + f'@printf "║    TCL=<path>          Custom waves TCL script               ║\\n"',
        T + f'@printf "║    VERBOSITY=<level>   UVM verbosity    (default: MEDIUM)    ║\\n"',
        T + f'@printf "║    TIMEOUT=<t>         UVM timeout      (default: {tout:<14})║\\n"',
        T + f'@printf "║    PLUSARGS=\'+a+b\'     Extra plusargs                        ║\\n"',
        T + f'@printf "║    VPLUSARGS=\'+k+v\'    Extra value-plusargs                  ║\\n"',
        T + f'@printf "║    DEFINES=\'+define+M\' Extra compile defines                 ║\\n"',
        T + f'@printf "║    COMP_OPTS=...       Extra compile options                 ║\\n"',
        T + f'@printf "║    SIM_OPTS=...        Extra simulation options              ║\\n"',
        T + f'@printf "╠══════════════════════════════════════════════════════════════╣\\n"',
        T + f'@printf "║  EXAMPLES                                                    ║\\n"',
        T + f'@printf "║    make compile                                              ║\\n"',
        T + f'@printf "║    make sim TEST=sanity SEED=42 WAVES=1                      ║\\n"',
        T + f'@printf "║    make run TEST=apb_reg_test SEED=100 COV=1                 ║\\n"',
        T + f'@printf "║    make sim DEFINES=\'+define+DEBUG\' VERBOSITY=UVM_HIGH       ║\\n"',
        T + f'@printf "║    make sim PLUSARGS=\'+my_arg\' VPLUSARGS=\'+key+val\'          ║\\n"',
        T + f'@printf "║    make regress                                              ║\\n"',
        T + f'@printf "║    make cov_merge && make cov_report                         ║\\n"',
        T + f'@printf "║    make verdi TEST=sanity SEED=42                            ║\\n"',
        T + f'@printf "╚══════════════════════════════════════════════════════════════╝\\n"',
        T + '@printf "\\n"',
        "",
        "#------------------------------------------------------------------------------",
        "# show_config — print all current variable values",
        "#------------------------------------------------------------------------------",
        "show_config:",
        T + '@echo "=== Makefile Configuration — $(PROJECT) ==="',
        T + '@echo "  SIM_ROOT   = $(SIM_ROOT)"',
        T + '@echo "  PROJ_ROOT  = $(PROJ_ROOT)"',
        T + '@echo "  BUILD_DIR  = $(BUILD_DIR)"',
        T + '@echo "  RUN_DIR    = $(RUN_DIR)"',
        T + '@echo "  TEST       = $(TEST)"',
        T + '@echo "  SEED       = $(SEED)"',
        T + '@echo "  WAVES      = $(WAVES)"',
        T + '@echo "  COV        = $(COV)"',
        T + '@echo "  LOG        = $(LOG)"',
        T + '@echo "  TCL        = $(TCL)"',
        T + '@echo "  VERBOSITY  = $(VERBOSITY)"',
        T + '@echo "  TIMEOUT    = $(TIMEOUT)"',
        T + '@echo "  TIMESCALE  = $(TIMESCALE)"',
        T + '@echo "  PLUSARGS   = $(PLUSARGS)"',
        T + '@echo "  VPLUSARGS  = $(VPLUSARGS)"',
        T + '@echo "  DEFINES    = $(DEFINES)"',
        T + '@echo "  COMP_OPTS  = $(COMP_OPTS)"',
        T + '@echo "  SIM_OPTS   = $(SIM_OPTS)"',
        T + '@echo "  VCS_HOME   = $(VCS_HOME)"',
        T + '@echo "  VERDI_HOME = $(VERDI_HOME)"',
        T + '@echo "  UVM_HOME   = $(UVM_HOME)"',
        T + '@echo "  UVM_VER    = $(UVM_VER)"',
        T + '@echo ""',
        "",
        "##############################################################################",
        "# COMPILATION",
        "##############################################################################",
        "",
        "$(BUILD_DIR):",
        T + "@mkdir -p $(BUILD_DIR)",
        "",
        "#------------------------------------------------------------------------------",
        "# compile_rtl — vlogan RTL files only",
        "#------------------------------------------------------------------------------",
        "compile_rtl: $(BUILD_DIR)",
        T + '@echo ""',
        T + '@echo "══════════════════════════════════════════════"',
        T + '@echo "  [COMPILE_RTL] Compiling RTL sources"',
        T + '@echo "══════════════════════════════════════════════"',
        T + "$(VLOGAN) $(VLOGAN_RTL_FLAGS)",
        T + '@echo "  [COMPILE_RTL] DONE"',
        T + '@echo ""',
        "",
        "#------------------------------------------------------------------------------",
        "# compile_tb — vlogan TB files (depends on compile_rtl)",
        "#------------------------------------------------------------------------------",
        "compile_tb: compile_rtl",
        T + '@echo ""',
        T + '@echo "══════════════════════════════════════════════"',
        T + '@echo "  [COMPILE_TB] Compiling TB sources"',
        T + '@echo "══════════════════════════════════════════════"',
        T + "$(VLOGAN) $(VLOGAN_TB_FLAGS)",
        T + '@echo "  [COMPILE_TB] DONE"',
        T + '@echo ""',
        "",
        "#------------------------------------------------------------------------------",
        "# elab — elaborate compiled units → build/simv",
        "#------------------------------------------------------------------------------",
        "elab: compile_tb",
        T + '@echo ""',
        T + '@echo "══════════════════════════════════════════════"',
        T + '@echo "  [ELAB] Elaborating → $(BUILD_DIR)/simv"',
        T + '@echo "══════════════════════════════════════════════"',
        T + "$(VCS) $(ELAB_FLAGS) $(COV_ELAB_FLAGS) $(WAVE_ELAB)",
        T + '@echo "  [ELAB] DONE — simv at $(BUILD_DIR)/simv"',
        T + '@echo ""',
        "",
        "#------------------------------------------------------------------------------",
        "# compile — full compile: RTL + TB + elab",
        "#------------------------------------------------------------------------------",
        "compile: elab",
        T + '@echo ""',
        T + '@echo "══════════════════════════════════════════════"',
        T + '@echo "  [COMPILE] Full compile complete"',
        T + '@echo "  Shared simv: $(BUILD_DIR)/simv"',
        T + '@echo "══════════════════════════════════════════════"',
        T + '@echo ""',
        "",
        "##############################################################################",
        "# SIMULATION",
        "##############################################################################",
        "",
        "$(RUN_DIR):",
        T + "@mkdir -p $(RUN_DIR)",
        "",
        "#------------------------------------------------------------------------------",
        "# sim — run one test using the shared simv from BUILD_DIR",
        "#       Requires existing build/simv — run 'make compile' first",
        "#------------------------------------------------------------------------------",
        "sim: $(RUN_DIR)",
        T + "@if [ ! -f $(BUILD_DIR)/simv ]; then \\",
        T + '  echo ""; \\',
        T + '  echo "ERROR: $(BUILD_DIR)/simv not found."; \\',
        T + '  echo "       Run \'make compile\' first to build the shared simv."; \\',
        T + '  echo ""; \\',
        T + "  exit 1; \\",
        T + "fi",
        T + '@echo ""',
        T + '@echo "══════════════════════════════════════════════"',
        T + '@echo "  [SIM] TEST=$(TEST)  SEED=$(SEED)"',
        T + '@echo "        WAVES=$(WAVES)  COV=$(COV)  LOG=$(LOG)"',
        T + '@echo "        RUN_DIR=$(RUN_DIR)"',
        T + '@echo "══════════════════════════════════════════════"',
        T + "cd $(RUN_DIR) && $(BUILD_DIR)/simv $(SIM_FLAGS)",
        T + '@echo "  [SIM] DONE"',
        T + '@if [ "$(LOG)" = "1" ]; then echo "  Log      : $(RUN_DIR)/simv.log"; fi',
        T + '@if [ "$(WAVES)" = "1" ]; then echo "  Waveform : $(RUN_DIR)/$(TEST).fsdb"; fi',
        T + '@if [ "$(COV)" = "1" ]; then echo "  Coverage : $(COV_DIR)"; fi',
        T + '@echo ""',
        "",
        "#------------------------------------------------------------------------------",
        "# run — compile from scratch then simulate",
        "#------------------------------------------------------------------------------",
        "run: compile sim",
        T + '@echo ""',
        T + '@echo "══════════════════════════════════════════════"',
        T + '@echo "  [RUN] Compile + Simulate complete"',
        T + '@echo "══════════════════════════════════════════════"',
        T + '@echo ""',
        "",
        "##############################################################################",
        "# REGRESSION",
        "##############################################################################",
        "",
        "regress:",
        T + '@echo ""',
        T + '@echo "══════════════════════════════════════════════"',
        T + '@echo "  [REGRESS] Starting regression suite"',
        T + '@echo "══════════════════════════════════════════════"',
        T + "@bash $(SIM_ROOT)/regression.sh",
        T + '@echo "  [REGRESS] Done — check $(LOG_DIR)"',
        T + '@echo ""',
        "",
        "##############################################################################",
        "# COVERAGE",
        "##############################################################################",
        "",
        "cov_merge:",
        T + '@echo ""',
        T + '@echo "══════════════════════════════════════════════"',
        T + '@echo "  [COV_MERGE] Merging coverage databases"',
        T + '@echo "══════════════════════════════════════════════"',
        T + "@mkdir -p $(COV_BASE)/merged",
        T + "$(URG) -dir $(COV_BASE)/*.vdb \\",
        T + "       -dbname $(COV_BASE)/merged/merged.vdb \\",
        T + "       -report $(COV_BASE)/merged/urgReport \\",
        T + "       -format both",
        T + '@echo "  [COV_MERGE] Report: $(COV_BASE)/merged/urgReport"',
        T + '@echo ""',
        "",
        "cov_report:",
        T + '@echo ""',
        T + '@echo "══════════════════════════════════════════════"',
        T + '@echo "  [COV_REPORT] Opening Verdi coverage viewer"',
        T + '@echo "══════════════════════════════════════════════"',
        T + "$(VERDI) -cov -covdir $(COV_BASE)/merged/merged.vdb &",
        T + '@echo "  [COV_REPORT] Verdi launched (background)"',
        T + '@echo ""',
        "",
        "##############################################################################",
        "# WAVEFORM",
        "##############################################################################",
        "",
        "verdi:",
        T + "@FSDB=$(RUN_DIR)/$(TEST).fsdb; \\",
        T + 'if [ ! -f "$$FSDB" ]; then \\',
        T + '  echo ""; \\',
        T + '  echo "WARNING: FSDB not found: $$FSDB"; \\',
        T + '  echo "         Run: make sim TEST=$(TEST) SEED=$(SEED) WAVES=1"; \\',
        T + '  echo ""; \\',
        T + "else \\",
        T + '  echo ""; \\',
        T + '  echo "══════════════════════════════════════════════"; \\',
        T + '  echo "  [VERDI] Opening $$FSDB"; \\',
        T + '  echo "══════════════════════════════════════════════"; \\',
        T + "  $(VERDI) -ssf $$FSDB -nologo & \\",
        T + "fi",
        "",
        "##############################################################################",
        "# CLEANUP",
        "##############################################################################",
        "",
        "clean_logs:",
        T + '@echo "=== [CLEAN_LOGS] Removing .log files ==="',
        T + "@find $(RUN_BASE) -name '*.log' -delete 2>/dev/null || true",
        T + "@find $(SIM_ROOT) -maxdepth 1 -name '*.log' -delete 2>/dev/null || true",
        T + '@echo "=== Done ==="',
        "",
        "clean_run:",
        T + '@echo "=== [CLEAN_RUN] Removing run/ ==="',
        T + "@rm -rf $(RUN_BASE)",
        T + '@echo "=== Done ==="',
        "",
        "clean_cov:",
        T + '@echo "=== [CLEAN_COV] Removing cov/ ==="',
        T + "@rm -rf $(COV_BASE)",
        T + '@echo "=== Done ==="',
        "",
        "clean_build:",
        T + '@echo "=== [CLEAN_BUILD] Removing build/ ==="',
        T + "@rm -rf $(BUILD_DIR)",
        T + '@echo "=== Done — run \'make compile\' to rebuild ==="',
        "",
        "clean: clean_run clean_cov clean_build",
        T + "@find $(SIM_ROOT) -name '*.log'     -delete 2>/dev/null || true",
        T + "@find $(SIM_ROOT) -name '*.fsdb'    -delete 2>/dev/null || true",
        T + "@find $(SIM_ROOT) -name 'ucli.key'  -delete 2>/dev/null || true",
        T + "@find $(SIM_ROOT) -name 'inter.vpd' -delete 2>/dev/null || true",
        T + "@find $(SIM_ROOT) -name '*.vpd'     -delete 2>/dev/null || true",
        T + "@find $(SIM_ROOT) -name 'novas.*'   -delete 2>/dev/null || true",
        T + '@echo "=== [CLEAN] All generated files removed — ready for fresh start ==="',
        "",
    ]
    return "\n".join(lines)


def gen_regression_sh(cfg, proj_root):
    p      = cfg["project_name"]
    pr     = str(proj_root)
    tests  = cfg.get("regression_tests", ["sanity"])
    seeds  = cfg.get("regression_seeds",  [1, 2, 3, 4, 5])

    test_block = "\n".join(
        f'  run_test "{t}" "{s}"'
        for t in tests
        for s in seeds
    )

    return (
        "#!/bin/bash\n"
        "##############################################################################\n"
        f"# regression.sh — {p} DV Regression Script\n"
        f"# Generated by dv-env-setup (S4)   Date: {TODAY}\n"
        "# Usage: bash regression.sh [COV=1] [WAVES=0]\n"
        "##############################################################################\n\n"
        'SIM_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"\n'
        f'BUILD_DIR="${{SIM_ROOT}}/build"\n'
        f'LOG_DIR="${{SIM_ROOT}}/logs"\n'
        'COV="${COV:-0}"\n'
        'WAVES="${WAVES:-0}"\n'
        'PASS=0\n'
        'FAIL=0\n\n'
        'mkdir -p "${LOG_DIR}"\n'
        'LOGFILE="${LOG_DIR}/regression_$(date +%Y%m%d_%H%M%S).log"\n\n'
        "log() { echo \"$@\" | tee -a \"${LOGFILE}\"; }\n\n"
        "run_test() {\n"
        "  local test=\"$1\"\n"
        "  local seed=\"$2\"\n"
        "  log \"  Running: TEST=${test} SEED=${seed}\"\n"
        '  if make -C "${SIM_ROOT}" sim TEST="${test}" SEED="${seed}" \\\n'
        '         COV="${COV}" WAVES="${WAVES}" LOG=1 > /dev/null 2>&1; then\n'
        '    log "  [PASS] ${test} seed=${seed}"\n'
        "    ((PASS++))\n"
        "  else\n"
        '    log "  [FAIL] ${test} seed=${seed} — check ${SIM_ROOT}/run/${test}_${seed}/simv.log"\n'
        "    ((FAIL++))\n"
        "  fi\n"
        "}\n\n"
        "# ─── Prerequisite check ──────────────────────────────────────────────────────\n"
        'if [ ! -f "${BUILD_DIR}/simv" ]; then\n'
        '  echo "ERROR: ${BUILD_DIR}/simv not found — run \'make compile\' first"\n'
        "  exit 1\n"
        "fi\n\n"
        "log \"\"\n"
        "log \"╔═══════════════════════════════════════════════════════╗\"\n"
        f'log "║  {p} DV Regression"\n'
        "log \"║  Started: $(date)\"\n"
        "log \"╚═══════════════════════════════════════════════════════╝\"\n"
        "log \"\"\n\n"
        "# ─── Test runs ───────────────────────────────────────────────────────────────\n"
        f"{test_block}\n\n"
        "# ─── Summary ─────────────────────────────────────────────────────────────────\n"
        "log \"\"\n"
        "log \"╔═══════════════════════════════════════════════════════╗\"\n"
        "log \"║  Regression Complete\"\n"
        'log "║  PASS  : ${PASS}"\n'
        'log "║  FAIL  : ${FAIL}"\n'
        'log "║  Total : $((PASS + FAIL))"\n'
        "log \"╚═══════════════════════════════════════════════════════╝\"\n"
        "log \"\"\n\n"
        'if [ "${FAIL}" -gt 0 ]; then\n'
        '  log "REGRESSION FAILED — ${FAIL} test(s) failed"\n'
        "  exit 1\n"
        "else\n"
        '  log "REGRESSION PASSED"\n'
        "  exit 0\n"
        "fi\n"
    )


# ─── UVM skeleton files ───────────────────────────────────────────────────────

def gen_tb_top(cfg):
    p = cfg["project_name"]
    ts = cfg.get("timescale", "1ns/1ps")
    return (
        f"`timescale {ts}\n"
        f"// {p}_tb_top.sv — UVM Testbench Top Module\n"
        f"// Generated by dv-env-setup (S4)   Date: {TODAY}\n"
        "// TODO: Connect DUT ports and interfaces\n\n"
        f"module {p}_tb_top;\n\n"
        "  import uvm_pkg::*;\n"
        '  `include "uvm_macros.svh"\n'
        f"  import {p}_env_pkg::*;\n\n"
        "  //------------------------------------------------------------------------\n"
        "  // Clock and reset\n"
        "  //------------------------------------------------------------------------\n"
        "  logic clk;    // TODO: update frequency per spec\n"
        "  logic rst_n;\n\n"
        "  initial clk = 1'b0;\n"
        "  always  #5 clk = ~clk;  // 100 MHz — update per spec\n\n"
        "  initial begin\n"
        "    rst_n = 1'b0;\n"
        "    repeat(10) @(posedge clk);\n"
        "    rst_n = 1'b1;\n"
        "  end\n\n"
        "  //------------------------------------------------------------------------\n"
        "  // Interfaces\n"
        "  // TODO: instantiate all interfaces from your spec\n"
        "  //------------------------------------------------------------------------\n"
        f"  // {p}_if u_{p}_if (.clk(clk), .rst_n(rst_n));\n\n"
        "  //------------------------------------------------------------------------\n"
        "  // DUT instantiation\n"
        "  // TODO: connect DUT ports to interface signals\n"
        "  //------------------------------------------------------------------------\n"
        f"  // {p} u_dut (\n"
        "  //   .clk   (clk),\n"
        "  //   .rst_n (rst_n),\n"
        "  //   // ... connect remaining ports\n"
        "  // );\n\n"
        "  //------------------------------------------------------------------------\n"
        "  // Bind assertions (optional)\n"
        "  //------------------------------------------------------------------------\n"
        f"  // bind {p} {p}_sva u_{p}_sva (.*);\n\n"
        "  //------------------------------------------------------------------------\n"
        "  // UVM test launch\n"
        "  //------------------------------------------------------------------------\n"
        "  initial begin\n"
        "    // Set virtual interfaces in config_db\n"
        f"    // uvm_config_db #(virtual {p}_if)::set(null, \"uvm_test_top.*\", \"vif\", u_{p}_if);\n\n"
        "    // Launch test (name from +UVM_TESTNAME)\n"
        "    run_test();\n"
        "  end\n\n"
        "  //------------------------------------------------------------------------\n"
        "  // Safety watchdog\n"
        "  //------------------------------------------------------------------------\n"
        "  initial begin\n"
        "    #100ms;\n"
        '    `uvm_fatal("TB_TIMEOUT", "Simulation exceeded 100ms — check UVM_TIMEOUT")\n'
        "  end\n\n"
        f"endmodule : {p}_tb_top\n"
    )


def gen_if(cfg):
    p  = cfg["project_name"]
    ts = cfg.get("timescale", "1ns/1ps")
    return (
        f"`timescale {ts}\n"
        f"// {p}_if.sv — Interface Placeholder\n"
        f"// Generated by dv-env-setup (S4)   Date: {TODAY}\n"
        "// TODO: Replace with actual interface signals from your spec\n\n"
        f"interface {p}_if (input logic clk, input logic rst_n);\n\n"
        "  // TODO: Add signals matching DUT ports\n"
        "  // logic        valid;\n"
        "  // logic        ready;\n"
        "  // logic [31:0] data;\n"
        "  // logic [3:0]  strb;\n\n"
        "  //------------------------------------------------------------------------\n"
        "  // Clocking blocks\n"
        "  //------------------------------------------------------------------------\n"
        "  // clocking driver_cb @(posedge clk);\n"
        "  //   default input #1 output #1;\n"
        "  //   output valid, data, strb;\n"
        "  //   input  ready;\n"
        "  // endclocking\n\n"
        "  // clocking monitor_cb @(posedge clk);\n"
        "  //   default input #1;\n"
        "  //   input valid, ready, data, strb;\n"
        "  // endclocking\n\n"
        "  //------------------------------------------------------------------------\n"
        "  // Modports\n"
        "  //------------------------------------------------------------------------\n"
        "  // modport dut_mp    (input clk, rst_n, valid, data, strb, output ready);\n"
        "  // modport driver_mp (clocking driver_cb, input rst_n);\n"
        "  // modport monitor_mp(clocking monitor_cb, input rst_n);\n\n"
        f"endinterface : {p}_if\n"
    )


def gen_env_pkg(cfg):
    p = cfg["project_name"]
    return (
        f"// {p}_env_pkg.sv — Environment Package\n"
        f"// Generated by dv-env-setup (S4)   Date: {TODAY}\n"
        "// Import all DV environment classes in dependency order.\n\n"
        f"package {p}_env_pkg;\n\n"
        "  import uvm_pkg::*;\n"
        '  `include "uvm_macros.svh"\n\n'
        "  // 1. Configuration (no dependencies)\n"
        f'  `include "{p}_env_cfg.sv"\n\n'
        "  // 2. Scoreboard\n"
        f'  `include "{p}_scoreboard.sv"\n\n'
        "  // 3. Coverage collector\n"
        f'  `include "{p}_coverage.sv"\n\n'
        "  // 4. Sequences\n"
        f'  `include "{p}_base_seq.sv"\n\n'
        "  // 5. Tests\n"
        f'  `include "{p}_base_test.sv"\n'
        f'  `include "{p}_sanity_test.sv"\n\n'
        "  // 6. Environment (depends on all above)\n"
        f'  `include "{p}_env.sv"\n\n'
        f"endpackage : {p}_env_pkg\n"
    )


def gen_env_cfg(cfg):
    p = cfg["project_name"]
    return (
        f"// {p}_env_cfg.sv — Environment Configuration Object\n"
        f"// Generated by dv-env-setup (S4)   Date: {TODAY}\n\n"
        f"class {p}_env_cfg extends uvm_object;\n"
        f"  `uvm_object_utils({p}_env_cfg)\n\n"
        "  //------------------------------------------------------------------------\n"
        "  // Component enables\n"
        "  //------------------------------------------------------------------------\n"
        "  bit enable_scoreboard = 1'b1;\n"
        "  bit enable_coverage   = 1'b1;\n\n"
        "  // TODO: Add project-specific config fields, e.g.:\n"
        "  // virtual " + p + "_if  vif;             // virtual interface handle\n"
        "  // int unsigned num_transactions = 100;\n"
        "  // bit          check_protocol   = 1'b1;\n"
        "  // logic [31:0] base_addr        = 32'h0000_0000;\n\n"
        "  //------------------------------------------------------------------------\n"
        f"  function new(string name = \"{p}_env_cfg\");\n"
        "    super.new(name);\n"
        "  endfunction\n\n"
        "  function void print_cfg();\n"
        f"    `uvm_info(\"CFG\", $sformatf(\"enable_scoreboard=%0b enable_coverage=%0b\",\n"
        "              enable_scoreboard, enable_coverage), UVM_MEDIUM)\n"
        "  endfunction\n\n"
        f"endclass : {p}_env_cfg\n"
    )


def gen_scoreboard(cfg):
    p = cfg["project_name"]
    return (
        f"// {p}_scoreboard.sv — UVM Scoreboard\n"
        f"// Generated by dv-env-setup (S4)   Date: {TODAY}\n"
        "// TODO: Connect analysis ports and implement data checks from S2 checker plan\n\n"
        f"class {p}_scoreboard extends uvm_scoreboard;\n"
        f"  `uvm_component_utils({p}_scoreboard)\n\n"
        "  // Analysis imports — connect from monitors\n"
        "  // uvm_analysis_imp #(my_trans, " + p + "_scoreboard) expected_ap;\n"
        "  // uvm_analysis_imp #(my_trans, " + p + "_scoreboard) actual_ap;\n\n"
        "  // Check counters\n"
        "  int unsigned checks_passed = 0;\n"
        "  int unsigned checks_failed = 0;\n\n"
        "  //------------------------------------------------------------------------\n"
        f"  function new(string name = \"{p}_scoreboard\", uvm_component parent = null);\n"
        "    super.new(name, parent);\n"
        "  endfunction\n\n"
        "  function void build_phase(uvm_phase phase);\n"
        "    super.build_phase(phase);\n"
        "    // expected_ap = new(\"expected_ap\", this);\n"
        "    // actual_ap   = new(\"actual_ap\",   this);\n"
        "  endfunction\n\n"
        "  // TODO: Implement write() for each analysis port\n"
        "  // function void write(my_trans t);\n"
        "  //   // Compare actual vs expected, increment counters\n"
        "  //   if (actual == expected) checks_passed++;\n"
        "  //   else begin checks_failed++; `uvm_error(\"SB\", ...) end\n"
        "  // endfunction\n\n"
        "  //------------------------------------------------------------------------\n"
        "  function void report_phase(uvm_phase phase);\n"
        "    if (checks_failed > 0)\n"
        "      `uvm_error(\"SB_REPORT\", $sformatf(\n"
        "        \"SCOREBOARD FAIL: %0d passed, %0d FAILED\",\n"
        "        checks_passed, checks_failed))\n"
        "    else\n"
        "      `uvm_info(\"SB_REPORT\", $sformatf(\n"
        "        \"SCOREBOARD PASS: %0d checks passed\", checks_passed), UVM_NONE)\n"
        "  endfunction\n\n"
        f"endclass : {p}_scoreboard\n"
    )


def gen_coverage(cfg):
    p = cfg["project_name"]
    return (
        f"// {p}_coverage.sv — Functional Coverage Collector\n"
        f"// Generated by dv-env-setup (S4)   Date: {TODAY}\n"
        "// TODO: Populate covergroups from S2 testplan coverage plan\n\n"
        f"class {p}_coverage extends uvm_subscriber #(uvm_sequence_item);\n"
        f"  `uvm_component_utils({p}_coverage)\n\n"
        "  //------------------------------------------------------------------------\n"
        "  // Covergroups — replace with actual covergroups from S2 testplan\n"
        "  //------------------------------------------------------------------------\n"
        "  // covergroup cg_<feature> @(posedge clk);\n"
        "  //   cp_<signal>: coverpoint trans.<field> {\n"
        "  //     bins <name>     = {<values>};\n"
        "  //     illegal_bins x  = {<illegal>};\n"
        "  //   }\n"
        "  //   cx_a_x_b: cross cp_<a>, cp_<b>;\n"
        "  // endgroup\n\n"
        "  //------------------------------------------------------------------------\n"
        f"  function new(string name = \"{p}_coverage\", uvm_component parent = null);\n"
        "    super.new(name, parent);\n"
        "    // Instantiate covergroups: cg_<feature> = new();\n"
        "  endfunction\n\n"
        "  function void write(uvm_sequence_item t);\n"
        "    // Sample covergroups: cg_<feature>.sample();\n"
        "  endfunction\n\n"
        f"endclass : {p}_coverage\n"
    )


def gen_env(cfg):
    p = cfg["project_name"]
    return (
        f"// {p}_env.sv — UVM Environment\n"
        f"// Generated by dv-env-setup (S4)   Date: {TODAY}\n\n"
        f"class {p}_env extends uvm_env;\n"
        f"  `uvm_component_utils({p}_env)\n\n"
        "  //------------------------------------------------------------------------\n"
        f"  {p}_env_cfg   cfg;\n"
        f"  {p}_scoreboard scoreboard;\n"
        f"  {p}_coverage   coverage;\n"
        "  // TODO: Add agent handles, e.g.:\n"
        "  // <proto>_agent  m_<proto>_agent;\n\n"
        "  //------------------------------------------------------------------------\n"
        f"  function new(string name = \"{p}_env\", uvm_component parent = null);\n"
        "    super.new(name, parent);\n"
        "  endfunction\n\n"
        "  //------------------------------------------------------------------------\n"
        "  function void build_phase(uvm_phase phase);\n"
        "    super.build_phase(phase);\n"
        "    // Retrieve config from config_db (set by test)\n"
        f"    if (!uvm_config_db #({p}_env_cfg)::get(this, \"\", \"cfg\", cfg)) begin\n"
        f"      cfg = {p}_env_cfg::type_id::create(\"cfg\");\n"
        '      `uvm_info("ENV", "cfg not in config_db — using defaults", UVM_MEDIUM)\n'
        "    end\n"
        "    if (cfg.enable_scoreboard)\n"
        f"      scoreboard = {p}_scoreboard::type_id::create(\"scoreboard\", this);\n"
        "    if (cfg.enable_coverage)\n"
        f"      coverage   = {p}_coverage::type_id::create(\"coverage\", this);\n"
        "    // TODO: Create agents:\n"
        "    // m_<proto>_agent = <proto>_agent::type_id::create(\"m_<proto>_agent\", this);\n"
        "  endfunction\n\n"
        "  //------------------------------------------------------------------------\n"
        "  function void connect_phase(uvm_phase phase);\n"
        "    super.connect_phase(phase);\n"
        "    // TODO: Connect monitor analysis ports:\n"
        "    // m_<proto>_agent.monitor.ap.connect(scoreboard.actual_ap);\n"
        "    // m_<proto>_agent.monitor.ap.connect(coverage.analysis_export);\n"
        "  endfunction\n\n"
        f"endclass : {p}_env\n"
    )


def gen_base_seq(cfg):
    p = cfg["project_name"]
    return (
        f"// {p}_base_seq.sv — Base Sequence\n"
        f"// Generated by dv-env-setup (S4)   Date: {TODAY}\n\n"
        f"class {p}_base_seq extends uvm_sequence #(uvm_sequence_item);\n"
        f"  `uvm_object_utils({p}_base_seq)\n\n"
        f"  function new(string name = \"{p}_base_seq\");\n"
        "    super.new(name);\n"
        "  endfunction\n\n"
        "  task pre_body();\n"
        "    // Common setup before body() — override in derived sequences\n"
        "  endtask\n\n"
        "  task post_body();\n"
        "    // Common cleanup after body() — override in derived sequences\n"
        "  endtask\n\n"
        "  task body();\n"
        f"    `uvm_fatal(\"BASE_SEQ\", \"{p}_base_seq::body() — use a derived sequence\")\n"
        "  endtask\n\n"
        f"endclass : {p}_base_seq\n"
    )


def gen_base_test(cfg):
    p = cfg["project_name"]
    return (
        f"// {p}_base_test.sv — Base UVM Test\n"
        f"// Generated by dv-env-setup (S4)   Date: {TODAY}\n\n"
        f"class {p}_base_test extends uvm_test;\n"
        f"  `uvm_component_utils({p}_base_test)\n\n"
        f"  {p}_env     env;\n"
        f"  {p}_env_cfg cfg;\n\n"
        f"  function new(string name = \"{p}_base_test\", uvm_component parent = null);\n"
        "    super.new(name, parent);\n"
        "  endfunction\n\n"
        "  function void build_phase(uvm_phase phase);\n"
        "    super.build_phase(phase);\n"
        f"    cfg = {p}_env_cfg::type_id::create(\"cfg\");\n"
        "    configure_env(cfg);\n"
        f"    uvm_config_db #({p}_env_cfg)::set(this, \"*\", \"cfg\", cfg);\n"
        f"    env = {p}_env::type_id::create(\"env\", this);\n"
        "  endfunction\n\n"
        "  // Override in derived tests to customize env configuration\n"
        f"  virtual function void configure_env({p}_env_cfg cfg);\n"
        "    cfg.enable_scoreboard = 1;\n"
        "    cfg.enable_coverage   = 1;\n"
        "    // TODO: set project-specific defaults\n"
        "  endfunction\n\n"
        "  task run_phase(uvm_phase phase);\n"
        "    phase.raise_objection(this);\n"
        '    `uvm_info("BASE_TEST", "run_phase — override in derived test", UVM_MEDIUM)\n'
        "    #100ns;\n"
        "    phase.drop_objection(this);\n"
        "  endtask\n\n"
        "  function void report_phase(uvm_phase phase);\n"
        "    uvm_report_server svr = uvm_report_server::get_server();\n"
        "    if (svr.get_severity_count(UVM_FATAL) > 0 ||\n"
        "        svr.get_severity_count(UVM_ERROR) > 0)\n"
        '      `uvm_info("TEST", "=== TEST FAILED ===", UVM_NONE)\n'
        "    else\n"
        '      `uvm_info("TEST", "=== TEST PASSED ===", UVM_NONE)\n'
        "  endfunction\n\n"
        f"endclass : {p}_base_test\n"
    )


def gen_sanity_test(cfg):
    p = cfg["project_name"]
    return (
        f"// {p}_sanity_test.sv — Sanity Test (DV-I milestone)\n"
        f"// Generated by dv-env-setup (S4)   Date: {TODAY}\n"
        "// First test: verifies basic TB infrastructure, clock, reset, env build\n\n"
        f"class {p}_sanity_test extends {p}_base_test;\n"
        f"  `uvm_component_utils({p}_sanity_test)\n\n"
        f"  function new(string name = \"{p}_sanity_test\", uvm_component parent = null);\n"
        "    super.new(name, parent);\n"
        "  endfunction\n\n"
        "  task run_phase(uvm_phase phase);\n"
        "    phase.raise_objection(this);\n"
        '    `uvm_info("SANITY", "Starting sanity test", UVM_MEDIUM)\n\n'
        "    // TODO: Replace with actual sanity sequence, e.g.:\n"
        f"    // {p}_base_seq seq = {p}_base_seq::type_id::create(\"seq\");\n"
        "    // seq.start(env.m_<proto>_agent.sequencer);\n\n"
        "    // Minimal check: allow a few clock cycles\n"
        "    repeat(100) @(posedge $root." + p + "_tb_top.clk);\n\n"
        '    `uvm_info("SANITY", "Sanity test complete", UVM_MEDIUM)\n'
        "    phase.drop_objection(this);\n"
        "  endtask\n\n"
        f"endclass : {p}_sanity_test\n"
    )


# ─── Output JSON ──────────────────────────────────────────────────────────────

def gen_env_data_json(cfg, proj_root):
    p  = cfg["project_name"]
    pr = str(proj_root)
    output = {
        "project_name":     p,
        "project_root":     pr,
        "generated_by":     "dv-env-setup",
        "date":             TODAY,
        "tool":             "vcs",
        "vcs_home":         cfg.get("vcs_home",       "<VCS_HOME>"),
        "verdi_home":       cfg.get("verdi_home",     "<VERDI_HOME>"),
        "uvm_home":         cfg.get("uvm_home",       "<UVM_HOME>"),
        "uvm_version":      cfg.get("uvm_version",    "1.2"),
        "license_server":   cfg.get("license_server", "<LICENSE_SERVER>"),
        "timescale":        cfg.get("timescale",      "1ns/1ps"),
        "default_timeout":  cfg.get("default_timeout","1ms"),
        "coverage_types":   cfg.get("coverage_types", "line+cond+branch+tgl+fsm"),
        "directory_structure": {
            "dv_root":      f"{pr}/dv",
            "tb_root":      f"{pr}/dv/tb",
            "env_root":     f"{pr}/dv/env",
            "seq_root":     f"{pr}/dv/seq_lib",
            "agents_root":  f"{pr}/dv/agents",
            "sim_root":     f"{pr}/dv/sim",
            "scripts_root": f"{pr}/dv/scripts",
            "cov_root":     f"{pr}/dv/cov",
            "build_dir":    f"{pr}/dv/sim/build",
            "run_base":     f"{pr}/dv/sim/run",
            "cov_base":     f"{pr}/dv/sim/cov",
        },
        "key_files": {
            "makefile":           f"{pr}/dv/sim/Makefile",
            "compile_f":          f"{pr}/dv/sim/compile.f",
            "rtl_f":              f"{pr}/dv/sim/rtl.f",
            "synopsys_sim_setup": f"{pr}/dv/sim/synopsys_sim.setup",
            "waves_tcl":          f"{pr}/dv/sim/waves.tcl",
            "regression_sh":      f"{pr}/dv/sim/regression.sh",
            "proj_cshrc":         f"{pr}/proj.cshrc",
            "proj_bashrc":        f"{pr}/proj.bashrc",
            "dot_env":            f"{pr}/.env",
        },
        "tb_skeleton_files": [
            f"{pr}/dv/tb/{p}_tb_top.sv",
            f"{pr}/dv/tb/{p}_if.sv",
            f"{pr}/dv/env/{p}_env_pkg.sv",
            f"{pr}/dv/env/{p}_env_cfg.sv",
            f"{pr}/dv/env/{p}_scoreboard.sv",
            f"{pr}/dv/env/{p}_coverage.sv",
            f"{pr}/dv/env/{p}_env.sv",
            f"{pr}/dv/seq_lib/{p}_base_seq.sv",
            f"{pr}/dv/seq_lib/{p}_base_test.sv",
            f"{pr}/dv/seq_lib/{p}_sanity_test.sv",
        ],
        "compile_command":    f"make -C {pr}/dv/sim compile",
        "sim_command":        f"make -C {pr}/dv/sim sim TEST=sanity SEED=1",
        "regression_command": f"make -C {pr}/dv/sim regress",
        "sources_used":       cfg.get("sources_used", []),
        "env_vars": {
            "PROJECT_ROOT": pr,
            "PROJECT_NAME": p,
            "DV_ROOT":      f"{pr}/dv",
            "RTL_ROOT":     f"{pr}/rtl",
            "SIM_ROOT":     f"{pr}/dv/sim",
            "VCS_HOME":     cfg.get("vcs_home",    "<VCS_HOME>"),
            "VERDI_HOME":   cfg.get("verdi_home",  "<VERDI_HOME>"),
            "UVM_HOME":     cfg.get("uvm_home",    "<UVM_HOME>"),
            "UVM_VERSION":  cfg.get("uvm_version", "1.2"),
        },
    }
    return json.dumps(output, indent=2)


# ─── Main ─────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="S4 DV Environment Setup Generator"
    )
    parser.add_argument("--config",    required=True,
                        help="Path to dv_env_config.json")
    parser.add_argument("--overwrite", action="store_true",
                        help="Overwrite existing files (default: skip)")
    args = parser.parse_args()

    cfg       = load_config(args.config)
    p         = cfg["project_name"]
    proj_root = Path(cfg.get("project_root", f"./{p}")).resolve()
    ow        = args.overwrite

    print(f"\n{'='*62}")
    print(f"  dv-env-setup (S4) — Generating {p} DV Environment")
    print(f"  Project root : {proj_root}")
    print(f"{'='*62}\n")

    # ── Directory scaffold ────────────────────────────────────────────────────
    print("[ Creating directory scaffold ]")
    dirs = [
        proj_root / "rtl",
        proj_root / "dv" / "tb",
        proj_root / "dv" / "env",
        proj_root / "dv" / "seq_lib",
        proj_root / "dv" / "agents",
        proj_root / "dv" / "sim" / "build",
        proj_root / "dv" / "sim" / "run",
        proj_root / "dv" / "sim" / "cov",
        proj_root / "dv" / "scripts",
        proj_root / "dv" / "cov",
    ]
    for d in dirs:
        mkdir(d)
        print(f"  [DIR]   {d}")

    # ── Environment files ─────────────────────────────────────────────────────
    print("\n[ Generating environment files ]")
    write_file(proj_root / "proj.cshrc",  gen_cshrc(cfg, proj_root),  ow)
    write_file(proj_root / "proj.bashrc", gen_bashrc(cfg, proj_root), ow)
    write_file(proj_root / ".env",        gen_dotenv(cfg, proj_root), ow)

    # ── VCS simulation files ──────────────────────────────────────────────────
    print("\n[ Generating VCS simulation files ]")
    sim = proj_root / "dv" / "sim"
    write_file(sim / "synopsys_sim.setup", gen_synopsys_sim_setup(cfg),    ow)
    write_file(sim / "rtl.f",             gen_rtl_f(cfg, proj_root),       ow)
    write_file(sim / "compile.f",         gen_compile_f(cfg, proj_root),   ow)
    write_file(sim / "Makefile",          gen_makefile(cfg, proj_root),     ow)
    write_file(sim / "waves.tcl",         gen_waves_tcl(cfg, proj_root),   ow)
    write_file(sim / "regression.sh",     gen_regression_sh(cfg, proj_root),ow)
    # Make regression.sh executable
    rsh = sim / "regression.sh"
    if rsh.exists():
        rsh.chmod(rsh.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP)

    # ── UVM TB skeleton files ─────────────────────────────────────────────────
    print("\n[ Generating UVM testbench skeleton files ]")
    tb  = proj_root / "dv" / "tb"
    env = proj_root / "dv" / "env"
    seq = proj_root / "dv" / "seq_lib"

    write_file(tb  / f"{p}_tb_top.sv",     gen_tb_top(cfg),    ow)
    write_file(tb  / f"{p}_if.sv",         gen_if(cfg),        ow)
    write_file(env / f"{p}_env_pkg.sv",    gen_env_pkg(cfg),   ow)
    write_file(env / f"{p}_env_cfg.sv",    gen_env_cfg(cfg),   ow)
    write_file(env / f"{p}_scoreboard.sv", gen_scoreboard(cfg),ow)
    write_file(env / f"{p}_coverage.sv",   gen_coverage(cfg),  ow)
    write_file(env / f"{p}_env.sv",        gen_env(cfg),       ow)
    write_file(seq / f"{p}_base_seq.sv",   gen_base_seq(cfg),  ow)
    write_file(seq / f"{p}_base_test.sv",  gen_base_test(cfg), ow)
    write_file(seq / f"{p}_sanity_test.sv",gen_sanity_test(cfg),ow)

    # ── Output JSON for S5+ ───────────────────────────────────────────────────
    print("\n[ Writing dv_env_data.json for downstream skills ]")
    out_json = f"/tmp/{p}_env_data_output.json"
    Path(out_json).write_text(gen_env_data_json(cfg, proj_root))
    print(f"  [GEN]   {out_json}")

    # ── Terminal summary ──────────────────────────────────────────────────────
    print(f"\n{'='*62}")
    print(f"  dv-env-setup (S4) — Complete")
    print(f"  Project   : {p}")
    print(f"  Root      : {proj_root}")
    print(f"{'─'*62}")
    print(f"  Generated :")
    print(f"    Directories      : {len(dirs)}")
    print(f"    Env files        : 3  (proj.cshrc, proj.bashrc, .env)")
    print(f"    VCS sim files    : 6  (Makefile, compile.f, rtl.f,")
    print(f"                          synopsys_sim.setup, waves.tcl,")
    print(f"                          regression.sh)")
    print(f"    UVM TB skeletons : 10")
    print(f"{'─'*62}")
    print(f"  Quick start:")
    print(f"    source {proj_root}/proj.cshrc")
    print(f"    cd {proj_root}/dv/sim")
    print(f"    make compile        # after adding RTL files to rtl.f")
    print(f"    make sim TEST=sanity SEED=1 WAVES=1")
    print(f"    make verdi TEST=sanity SEED=1")
    print(f"    make regress")
    print(f"    make cov_merge && make cov_report")
    print(f"{'─'*62}")
    print(f"  Next step: run /dv-tb-scaffold (S5) to generate agents")
    print(f"{'='*62}\n")


if __name__ == "__main__":
    main()
