#!/usr/bin/env python3
"""
generate_tb_scaffold.py — DV Skills S5 common generation script
Generates all UVM VIP components, RAL model, and environment files
from a dv_tb_scaffold_data.json configuration.

Usage:
    python3 generate_tb_scaffold.py --config /tmp/<proj>_tb_scaffold_data.json [--phase vips|ral|env|all]
    python3 generate_tb_scaffold.py --config /tmp/<proj>_tb_scaffold_data.json --phase all
"""

import json
import sys
import argparse
from pathlib import Path
from datetime import date
from textwrap import dedent, indent


# ── Helpers ────────────────────────────────────────────────────────────────────

def safe_write(path: Path, content: str) -> bool:
    """Write file only if it does not already exist. Returns True if written."""
    if path.exists():
        print(f"  SKIP (exists): {path}")
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    print(f"  WRITE: {path}")
    return True


def vip_class(vip_name: str, suffix: str, params: dict) -> str:
    """Return parameterized class name string."""
    data_w = params.get("DATA_WIDTH", 32)
    addr_w = params.get("ADDR_WIDTH", 32)
    return f"{vip_name}_{suffix} #(.DATA_WIDTH({data_w}), .ADDR_WIDTH({addr_w}))"


def param_decl(params: dict) -> str:
    """Return parameter declaration block."""
    lines = []
    for k, v in params.items():
        lines.append(f"  parameter int {k} = {v}")
    return ",\n".join(lines)


def header(vip_name: str, file_type: str, protocol: str, params: dict) -> str:
    data_w = params.get("DATA_WIDTH", 32)
    addr_w = params.get("ADDR_WIDTH", 32)
    return (f"// {vip_name.upper()} {file_type} — generated by dv-tb-scaffold (S5)\n"
            f"// Protocol: {protocol}  DATA_WIDTH={data_w}  ADDR_WIDTH={addr_w}\n"
            f"// Generated: {date.today()}  DO NOT edit generated sections.\n\n")


# ── VIP File Generators ────────────────────────────────────────────────────────

def gen_interface(vip: dict, dv_root: Path) -> None:
    vn    = vip["vip_name"]
    proto = vip["protocol"]
    p     = vip["parameters"]
    dw    = p.get("DATA_WIDTH", 32)
    aw    = p.get("ADDR_WIDTH", 32)
    sva   = vip.get("sva_from_testplan", [])

    # Build SVA block from testplan assertions
    sva_block = ""
    if sva:
        sva_lines = ["  // ── Protocol SVA (from testplan) ─────────────────────────────────"]
        for a in sva:
            chk_id = a.get("checker_id", "CHK_UNKNOWN")
            code   = a.get("assertion_code", f"  // TODO: {chk_id} assertion code")
            # indent each line of SVA
            indented = "\n".join(f"  {ln}" for ln in code.splitlines())
            sva_lines.append(indented)
        sva_block = "\n".join(sva_lines) + "\n"
    else:
        sva_block = (
            "  // ── Protocol SVA ─────────────────────────────────────────────────────\n"
            "  // TODO: Add inline SVA from testplan assertions here.\n"
            "  // SVA format:\n"
            "  //   property p_<name>;\n"
            "  //     @(posedge clk) disable iff (!rst_n)\n"
            "  //     <antecedent> |-> <consequent>;\n"
            "  //   endproperty\n"
            "  //   assert property (p_<name>) else\n"
            "  //     $error(\"[%m] <CHK_ID> violated at %0t\", $time);\n"
        )

    # Protocol-specific signals
    sig_block = _protocol_signals(proto, dw, aw)
    cb_driver, cb_monitor, modports = _protocol_clocking(proto, dw, aw)

    content = (
        header(vn, "Interface", proto, p) +
        f"interface {vn}_if #(\n"
        f"  parameter int DATA_WIDTH = {dw},\n"
        f"  parameter int ADDR_WIDTH = {aw}\n"
        f")(input logic clk, input logic rst_n);\n\n"
        f"  // ── Signal Declarations ─────────────────────────────────────────\n"
        f"{sig_block}\n"
        f"  // ── Clocking Block: Driver perspective ──────────────────────────\n"
        f"{cb_driver}\n"
        f"  // ── Clocking Block: Monitor perspective ─────────────────────────\n"
        f"{cb_monitor}\n"
        f"  // ── Modports ─────────────────────────────────────────────────────\n"
        f"{modports}\n"
        f"{sva_block}\n"
        f"endinterface : {vn}_if\n"
    )

    out = dv_root / "agents" / vn / f"{vn}_if.sv"
    safe_write(out, content)


def _protocol_signals(proto: str, dw: int, aw: int) -> str:
    """Return signal declarations for known protocols."""
    P = proto.upper()
    if "AXI4-STREAM" in P:
        return (
            f"  logic [DATA_WIDTH-1:0]   tdata;\n"
            f"  logic                    tvalid;\n"
            f"  logic                    tready;\n"
            f"  logic                    tlast;\n"
            f"  logic [DATA_WIDTH/8-1:0] tkeep;\n"
            f"  logic [DATA_WIDTH/8-1:0] tstrb;\n"
        )
    elif "AXI4-LITE" in P:
        return (
            f"  // Write address channel\n"
            f"  logic [ADDR_WIDTH-1:0]   awaddr; logic [2:0] awprot; logic awvalid; logic awready;\n"
            f"  // Write data channel\n"
            f"  logic [DATA_WIDTH-1:0]   wdata; logic [DATA_WIDTH/8-1:0] wstrb; logic wvalid; logic wready;\n"
            f"  // Write response channel\n"
            f"  logic [1:0]              bresp; logic bvalid; logic bready;\n"
            f"  // Read address channel\n"
            f"  logic [ADDR_WIDTH-1:0]   araddr; logic [2:0] arprot; logic arvalid; logic arready;\n"
            f"  // Read data channel\n"
            f"  logic [DATA_WIDTH-1:0]   rdata; logic [1:0] rresp; logic rvalid; logic rready;\n"
        )
    elif "AXI4" in P:
        return (
            f"  // Write address channel\n"
            f"  logic [3:0]              awid;  logic [ADDR_WIDTH-1:0] awaddr;\n"
            f"  logic [7:0]              awlen; logic [2:0] awsize; logic [1:0] awburst;\n"
            f"  logic                    awvalid; logic awready;\n"
            f"  // Write data channel\n"
            f"  logic [DATA_WIDTH-1:0]   wdata; logic [DATA_WIDTH/8-1:0] wstrb;\n"
            f"  logic                    wlast; logic wvalid; logic wready;\n"
            f"  // Write response channel\n"
            f"  logic [3:0]              bid; logic [1:0] bresp; logic bvalid; logic bready;\n"
            f"  // Read address channel\n"
            f"  logic [3:0]              arid; logic [ADDR_WIDTH-1:0] araddr;\n"
            f"  logic [7:0]              arlen; logic [2:0] arsize; logic [1:0] arburst;\n"
            f"  logic                    arvalid; logic arready;\n"
            f"  // Read data channel\n"
            f"  logic [3:0]              rid; logic [DATA_WIDTH-1:0] rdata;\n"
            f"  logic [1:0]              rresp; logic rlast; logic rvalid; logic rready;\n"
        )
    elif "AHB" in P:
        return (
            f"  logic [ADDR_WIDTH-1:0]   haddr;\n"
            f"  logic [2:0]              hburst;\n"
            f"  logic [2:0]              hsize;\n"
            f"  logic [1:0]              htrans;  // IDLE=0, BUSY=1, NONSEQ=2, SEQ=3\n"
            f"  logic [DATA_WIDTH-1:0]   hwdata;\n"
            f"  logic                    hwrite;\n"
            f"  logic [DATA_WIDTH-1:0]   hrdata;\n"
            f"  logic                    hready;\n"
            f"  logic                    hresp;   // 0=OKAY, 1=ERROR\n"
            f"  logic                    hsel;\n"
        )
    elif "APB" in P:
        return (
            f"  logic [ADDR_WIDTH-1:0]   paddr;\n"
            f"  logic                    psel;\n"
            f"  logic                    penable;\n"
            f"  logic                    pwrite;\n"
            f"  logic [DATA_WIDTH-1:0]   pwdata;\n"
            f"  logic [DATA_WIDTH-1:0]   prdata;\n"
            f"  logic                    pready;\n"
            f"  logic                    pslverr;\n"
            f"  logic [DATA_WIDTH/8-1:0] pstrb;   // APB4 only\n"
        )
    elif "SPI" in P:
        return (
            f"  logic  sclk;   // serial clock (driven by master)\n"
            f"  logic  mosi;   // master out, slave in\n"
            f"  logic  miso;   // master in, slave out\n"
            f"  logic  ss_n;   // slave select (active low)\n"
        )
    elif "I2C" in P:
        return (
            f"  logic  scl;   // serial clock (open-drain)\n"
            f"  logic  sda;   // serial data (open-drain, bidirectional)\n"
        )
    elif "UART" in P:
        return (
            f"  logic  txd;   // transmit data (DUT TX)\n"
            f"  logic  rxd;   // receive data  (DUT RX)\n"
            f"  logic  rts_n; // request to send (active low, optional)\n"
            f"  logic  cts_n; // clear to send   (active low, optional)\n"
        )
    elif "TILELINK" in P:
        return (
            f"  // TileLink Channel A (Request)\n"
            f"  logic [2:0]              a_opcode;\n"
            f"  logic [2:0]              a_param;\n"
            f"  logic [2:0]              a_size;\n"
            f"  logic [ADDR_WIDTH-1:0]   a_address;\n"
            f"  logic [DATA_WIDTH/8-1:0] a_mask;\n"
            f"  logic [DATA_WIDTH-1:0]   a_data;\n"
            f"  logic                    a_valid; logic a_ready;\n"
            f"  // TileLink Channel D (Response)\n"
            f"  logic [2:0]              d_opcode;\n"
            f"  logic [1:0]              d_param;\n"
            f"  logic [2:0]              d_size;\n"
            f"  logic [DATA_WIDTH-1:0]   d_data;\n"
            f"  logic                    d_error;\n"
            f"  logic                    d_valid; logic d_ready;\n"
        )
    else:
        return (
            f"  // TODO: Add {proto} protocol signal declarations here\n"
            f"  // Refer to dv_spec_summary.json proprietary_interfaces section\n"
        )


def _protocol_clocking(proto: str, dw: int, aw: int):
    """Return (driver_clocking_block, monitor_clocking_block, modports) strings."""
    P = proto.upper()
    if "AXI4-LITE" in P or "AXI4" in P:
        drv = (
            "  clocking driver_cb @(posedge clk);\n"
            "    default input #1step output #1;\n"
            "    output awaddr, awprot, awvalid;\n"
            "    output wdata, wstrb, wvalid;\n"
            "    output bready;\n"
            "    output araddr, arprot, arvalid;\n"
            "    output rready;\n"
            "    input  awready, wready, bresp, bvalid;\n"
            "    input  arready, rdata, rresp, rvalid;\n"
            "  endclocking\n"
        )
        mon = (
            "  clocking monitor_cb @(posedge clk);\n"
            "    default input #1step;\n"
            "    input awaddr, awprot, awvalid, awready;\n"
            "    input wdata,  wstrb,  wvalid,  wready;\n"
            "    input bresp,  bvalid, bready;\n"
            "    input araddr, arprot, arvalid, arready;\n"
            "    input rdata,  rresp,  rvalid,  rready;\n"
            "  endclocking\n"
        )
        mods = (
            "  modport master_mp  (clocking driver_cb,  input rst_n);\n"
            "  modport slave_mp   (/* TODO: reverse of master_mp for slave DUT */\n"
            "                      input rst_n);\n"
            "  modport monitor_mp (clocking monitor_cb, input rst_n);\n"
        )
    elif "AHB" in P:
        drv = (
            "  clocking driver_cb @(posedge clk);\n"
            "    default input #1step output #1;\n"
            "    output haddr, hburst, hsize, htrans, hwdata, hwrite, hsel;\n"
            "    input  hrdata, hready, hresp;\n"
            "  endclocking\n"
        )
        mon = (
            "  clocking monitor_cb @(posedge clk);\n"
            "    default input #1step;\n"
            "    input haddr, hburst, hsize, htrans, hwdata, hwrite;\n"
            "    input hrdata, hready, hresp, hsel;\n"
            "  endclocking\n"
        )
        mods = (
            "  modport master_mp  (clocking driver_cb,  input rst_n);\n"
            "  modport slave_mp   (/* TODO: slave modport */\n"
            "                      input rst_n);\n"
            "  modport monitor_mp (clocking monitor_cb, input rst_n);\n"
        )
    elif "APB" in P:
        drv = (
            "  clocking driver_cb @(posedge clk);\n"
            "    default input #1step output #1;\n"
            "    output paddr, psel, penable, pwrite, pwdata, pstrb;\n"
            "    input  prdata, pready, pslverr;\n"
            "  endclocking\n"
        )
        mon = (
            "  clocking monitor_cb @(posedge clk);\n"
            "    default input #1step;\n"
            "    input paddr, psel, penable, pwrite, pwdata, pstrb;\n"
            "    input prdata, pready, pslverr;\n"
            "  endclocking\n"
        )
        mods = (
            "  modport master_mp  (clocking driver_cb,  input rst_n);\n"
            "  modport slave_mp   (/* TODO: slave modport */\n"
            "                      input rst_n);\n"
            "  modport monitor_mp (clocking monitor_cb, input rst_n);\n"
        )
    elif "SPI" in P:
        drv = (
            "  clocking driver_cb @(posedge clk);\n"
            "    default input #1step output #1;\n"
            "    output sclk, mosi, ss_n;\n"
            "    input  miso;\n"
            "  endclocking\n"
        )
        mon = (
            "  clocking monitor_cb @(posedge clk);\n"
            "    default input #1step;\n"
            "    input sclk, mosi, miso, ss_n;\n"
            "  endclocking\n"
        )
        mods = (
            "  modport master_mp  (clocking driver_cb,  input rst_n);\n"
            "  modport slave_mp   (/* TODO: SPI slave modport */\n"
            "                      input rst_n);\n"
            "  modport monitor_mp (clocking monitor_cb, input rst_n);\n"
        )
    elif "I2C" in P:
        drv = (
            "  clocking driver_cb @(posedge clk);\n"
            "    default input #1step output #1;\n"
            "    output scl;\n"
            "    inout  sda;  // open-drain — drive 0 or release (Z)\n"
            "  endclocking\n"
        )
        mon = (
            "  clocking monitor_cb @(posedge clk);\n"
            "    default input #1step;\n"
            "    input scl, sda;\n"
            "  endclocking\n"
        )
        mods = (
            "  modport master_mp  (clocking driver_cb,  input rst_n);\n"
            "  modport slave_mp   (/* TODO: I2C slave modport */\n"
            "                      input rst_n);\n"
            "  modport monitor_mp (clocking monitor_cb, input rst_n);\n"
        )
    else:
        drv = (
            "  clocking driver_cb @(posedge clk);\n"
            "    default input #1step output #1;\n"
            "    // TODO: list driven and sampled signals for this protocol\n"
            "  endclocking\n"
        )
        mon = (
            "  clocking monitor_cb @(posedge clk);\n"
            "    default input #1step;\n"
            "    // TODO: list all observed signals\n"
            "  endclocking\n"
        )
        mods = (
            "  modport master_mp  (clocking driver_cb,  input rst_n);\n"
            "  modport monitor_mp (clocking monitor_cb, input rst_n);\n"
        )
    return drv, mon, mods


def gen_seq_item(vip: dict, dv_root: Path) -> None:
    vn = vip["vip_name"]
    p  = vip["parameters"]
    dw = p.get("DATA_WIDTH", 32)
    aw = p.get("ADDR_WIDTH", 32)
    proto = vip["protocol"].upper()

    # Protocol-specific fields
    extra_fields = _seq_item_fields(proto)

    content = (
        header(vn, "Sequence Item", vip["protocol"], p) +
        f"class {vn}_seq_item #(\n"
        f"  parameter int DATA_WIDTH = {dw},\n"
        f"  parameter int ADDR_WIDTH = {aw}\n"
        f") extends uvm_sequence_item;\n\n"
        f"  `uvm_object_param_utils_begin({vn}_seq_item#(DATA_WIDTH, ADDR_WIDTH))\n"
        f"    `uvm_field_int(addr,         UVM_ALL_ON)\n"
        f"    `uvm_field_int(data,         UVM_ALL_ON)\n"
        f"    `uvm_field_enum({vn}_kind_e, kind, UVM_ALL_ON)\n"
        f"    `uvm_field_int(pkt_size,     UVM_ALL_ON)\n"
        f"    `uvm_field_enum(delay_type_e,delay_type, UVM_ALL_ON)\n"
        f"    `uvm_field_int(delay_val,    UVM_ALL_ON)\n"
        f"  `uvm_object_param_utils_end\n\n"
        f"  // ── Fields that change per transaction ──────────────────────────\n"
        f"  rand logic [ADDR_WIDTH-1:0] addr;\n"
        f"  rand logic [DATA_WIDTH-1:0] data;\n"
        f"  rand {vn}_kind_e            kind;\n"
        f"  rand int unsigned           pkt_size;    // number of beats\n"
        f"  rand delay_type_e           delay_type;  // ZERO / FIXED / RANDOM\n"
        f"  rand int unsigned           delay_val;   // inter-beat delay cycles\n"
        f"{extra_fields}\n"
        f"  // ── Constraints ──────────────────────────────────────────────────\n"
        f"  constraint c_delay {{\n"
        f"    if      (delay_type == ZERO)  delay_val == 0;\n"
        f"    else if (delay_type == FIXED) delay_val inside {{[1:10]}};\n"
        f"    else                          delay_val inside {{[0:20]}};\n"
        f"  }}\n"
        f"  constraint c_pkt_size {{ pkt_size inside {{[1:16]}}; }}\n\n"
        f"  function new(string name = \"{vn}_seq_item\");\n"
        f"    super.new(name);\n"
        f"  endfunction\n\n"
        f"  virtual function string convert2string();\n"
        f"    return $sformatf(\"[%s] addr=0x%0h data=0x%0h kind=%s pkt=%0d\",\n"
        f"                     get_type_name(), addr, data, kind.name(), pkt_size);\n"
        f"  endfunction\n"
        f"endclass\n"
    )
    safe_write(dv_root / "agents" / vn / f"{vn}_seq_item.sv", content)


def _seq_item_fields(proto: str) -> str:
    if "AXI4" in proto:
        return (
            "  rand logic [3:0]   id;          // transaction ID\n"
            "  rand logic [1:0]   burst;       // FIXED=0, INCR=1, WRAP=2\n"
            "  rand logic [7:0]   len;         // burst length -1 (AXI4 = 0..255)\n"
            "  rand logic [2:0]   size;        // 2^size bytes per beat\n"
            "  rand logic [1:0]   resp;        // OKAY/EXOKAY/SLVERR/DECERR\n"
        )
    elif "AHB" in proto:
        return (
            "  rand logic [2:0]   hburst;      // SINGLE/INCR/WRAP4/INCR4/...\n"
            "  rand logic [2:0]   hsize;       // 2^hsize bytes per beat\n"
            "  rand logic [1:0]   htrans;      // IDLE/BUSY/NONSEQ/SEQ\n"
        )
    elif "APB" in proto:
        return (
            "  // APB is simple: addr/data/write covered by base fields\n"
        )
    elif "SPI" in proto:
        return (
            "  rand logic [1:0]   cpol_cpha;   // SPI mode: 0=0/0,1=0/1,2=1/0,3=1/1\n"
            "  rand logic [7:0]   frame_data;  // per-frame data (8-bit default)\n"
        )
    elif "I2C" in proto:
        return (
            "  rand logic [9:0]   dev_addr;    // 7-bit [6:0] or 10-bit [9:0]\n"
            "  rand bit            addr_10bit;  // 0=7-bit, 1=10-bit\n"
            "  rand bit            read_write;  // 0=write, 1=read\n"
        )
    elif "UART" in proto:
        return (
            "  rand logic [7:0]   payload;     // data byte\n"
            "  rand logic [1:0]   parity_mode; // 0=none, 1=even, 2=odd\n"
            "  rand int unsigned  baud_rate;   // baud rate in bps\n"
        )
    elif "TILELINK" in proto:
        return (
            "  rand logic [2:0]   opcode;      // TileLink A-channel opcode\n"
            "  rand logic [2:0]   tl_size;     // log2 of bytes\n"
            "  rand logic [2:0]   param;       // opcode-specific parameter\n"
        )
    else:
        return "  // TODO: add protocol-specific transaction fields\n"


def gen_cfg(vip: dict, dv_root: Path) -> None:
    vn = vip["vip_name"]
    p  = vip["parameters"]
    dw = p.get("DATA_WIDTH", 32)
    aw = p.get("ADDR_WIDTH", 32)

    content = (
        header(vn, "Config Class", vip["protocol"], p) +
        f"// Fields here remain constant for the duration of a test run.\n"
        f"class {vn}_cfg extends uvm_object;\n"
        f"  `uvm_object_utils_begin({vn}_cfg)\n"
        f"    `uvm_field_enum(uvm_active_passive_enum, is_active, UVM_ALL_ON)\n"
        f"    `uvm_field_int(error_inject_en, UVM_ALL_ON)\n"
        f"  `uvm_object_utils_end\n\n"
        f"  uvm_active_passive_enum is_active       = UVM_ACTIVE;\n"
        f"  bit                     error_inject_en = 0;\n"
        f"  int unsigned            data_width      = {dw};\n"
        f"  int unsigned            addr_width      = {aw};\n"
        f"  // TODO: add protocol-specific constant config fields\n"
        f"  // e.g. spi_mode, i2c_speed, axi_outstanding_txns, uart_baud\n\n"
        f"  function new(string name = \"{vn}_cfg\");\n"
        f"    super.new(name);\n"
        f"  endfunction\n"
        f"endclass\n"
    )
    safe_write(dv_root / "agents" / vn / f"{vn}_cfg.sv", content)


def gen_driver(vip: dict, dv_root: Path) -> None:
    vn = vip["vip_name"]
    p  = vip["parameters"]
    dw = p.get("DATA_WIDTH", 32)
    aw = p.get("ADDR_WIDTH", 32)

    content = (
        header(vn, "Driver BFM", vip["protocol"], p) +
        f"class {vn}_driver #(\n"
        f"  parameter int DATA_WIDTH = {dw},\n"
        f"  parameter int ADDR_WIDTH = {aw}\n"
        f") extends uvm_driver #({vn}_seq_item#(DATA_WIDTH, ADDR_WIDTH));\n\n"
        f"  `uvm_component_param_utils({vn}_driver#(DATA_WIDTH, ADDR_WIDTH))\n\n"
        f"  typedef {vn}_seq_item #(DATA_WIDTH, ADDR_WIDTH) seq_item_t;\n\n"
        f"  virtual {vn}_if #(DATA_WIDTH, ADDR_WIDTH) vif;\n"
        f"  {vn}_cfg cfg;\n\n"
        f"  function new(string name, uvm_component parent);\n"
        f"    super.new(name, parent);\n"
        f"  endfunction\n\n"
        f"  function void build_phase(uvm_phase phase);\n"
        f"    super.build_phase(phase);\n"
        f"    if (!uvm_config_db #(virtual {vn}_if#(DATA_WIDTH,ADDR_WIDTH))\n"
        f"        ::get(this, \"\", \"vif\", vif))\n"
        f"      `uvm_fatal(\"NO_VIF\", {{\"vif not found for \", get_full_name()}})\n"
        f"    if (!uvm_config_db #({vn}_cfg)::get(this, \"\", \"cfg\", cfg))\n"
        f"      `uvm_fatal(\"NO_CFG\", {{\"cfg not found for \", get_full_name()}})\n"
        f"  endfunction\n\n"
        f"  task run_phase(uvm_phase phase);\n"
        f"    drive_idle();\n"
        f"    @(posedge vif.clk iff vif.rst_n);  // wait for reset deassert\n"
        f"    forever begin\n"
        f"      seq_item_port.get_next_item(req);\n"
        f"      `uvm_info(get_type_name(),\n"
        f"        $sformatf(\"Driving: %s\", req.convert2string()), UVM_HIGH)\n"
        f"      if (req.delay_type != ZERO) repeat(req.delay_val) @(posedge vif.clk);\n"
        f"      drive_item(req);\n"
        f"      seq_item_port.item_done();\n"
        f"    end\n"
        f"  endtask\n\n"
        f"  task drive_idle();\n"
        f"    // TODO: drive all interface signals to protocol-defined idle state\n"
        f"    // {vip['protocol']} idle: [describe idle conditions]\n"
        f"    @(posedge vif.clk);\n"
        f"  endtask\n\n"
        f"  task drive_item(seq_item_t item);\n"
        f"    // TODO: implement full {vip['protocol']} state machine for one transaction\n"
        f"    // Phase 1: [address/arbitration phase]\n"
        f"    // Phase 2: [data phase]\n"
        f"    // Phase 3: [response/completion phase]\n"
        f"    @(posedge vif.clk);\n"
        f"  endtask\n"
        f"endclass\n"
    )
    safe_write(dv_root / "agents" / vn / f"{vn}_driver.sv", content)


def gen_monitor(vip: dict, dv_root: Path) -> None:
    vn = vip["vip_name"]
    p  = vip["parameters"]
    dw = p.get("DATA_WIDTH", 32)
    aw = p.get("ADDR_WIDTH", 32)

    content = (
        header(vn, "Monitor", vip["protocol"], p) +
        f"class {vn}_monitor #(\n"
        f"  parameter int DATA_WIDTH = {dw},\n"
        f"  parameter int ADDR_WIDTH = {aw}\n"
        f") extends uvm_monitor;\n\n"
        f"  `uvm_component_param_utils({vn}_monitor#(DATA_WIDTH, ADDR_WIDTH))\n\n"
        f"  typedef {vn}_seq_item #(DATA_WIDTH, ADDR_WIDTH) seq_item_t;\n\n"
        f"  virtual {vn}_if #(DATA_WIDTH, ADDR_WIDTH) vif;\n"
        f"  {vn}_cfg cfg;\n"
        f"  uvm_analysis_port #(seq_item_t) ap;\n\n"
        f"  function new(string name, uvm_component parent);\n"
        f"    super.new(name, parent);\n"
        f"    ap = new(\"ap\", this);\n"
        f"  endfunction\n\n"
        f"  function void build_phase(uvm_phase phase);\n"
        f"    super.build_phase(phase);\n"
        f"    if (!uvm_config_db #(virtual {vn}_if#(DATA_WIDTH,ADDR_WIDTH))\n"
        f"        ::get(this, \"\", \"vif\", vif))\n"
        f"      `uvm_fatal(\"NO_VIF\", {{\"vif not found for \", get_full_name()}})\n"
        f"    if (!uvm_config_db #({vn}_cfg)::get(this, \"\", \"cfg\", cfg))\n"
        f"      `uvm_fatal(\"NO_CFG\", {{\"cfg not found for \", get_full_name()}})\n"
        f"  endfunction\n\n"
        f"  task run_phase(uvm_phase phase);\n"
        f"    @(posedge vif.clk iff vif.rst_n);\n"
        f"    forever begin\n"
        f"      seq_item_t item = seq_item_t::type_id::create(\"item\");\n"
        f"      collect_transaction(item);\n"
        f"      `uvm_info(get_type_name(),\n"
        f"        $sformatf(\"Observed: %s\", item.convert2string()), UVM_HIGH)\n"
        f"      ap.write(item);\n"
        f"    end\n"
        f"  endtask\n\n"
        f"  task collect_transaction(seq_item_t item);\n"
        f"    // TODO: sample {vip['protocol']} interface to reconstruct one transaction\n"
        f"    // 1. Wait for transaction start condition (e.g. valid & ready)\n"
        f"    // 2. Capture address phase signals\n"
        f"    // 3. Capture data phase signals\n"
        f"    // 4. Capture response/completion signals\n"
        f"    // 5. Populate item fields from captured values\n"
        f"    @(posedge vif.clk);\n"
        f"  endtask\n"
        f"endclass\n"
    )
    safe_write(dv_root / "agents" / vn / f"{vn}_monitor.sv", content)


def gen_sequencer(vip: dict, dv_root: Path) -> None:
    vn = vip["vip_name"]
    p  = vip["parameters"]
    dw = p.get("DATA_WIDTH", 32)
    aw = p.get("ADDR_WIDTH", 32)

    content = (
        header(vn, "Sequencer", vip["protocol"], p) +
        f"class {vn}_sequencer #(\n"
        f"  parameter int DATA_WIDTH = {dw},\n"
        f"  parameter int ADDR_WIDTH = {aw}\n"
        f") extends uvm_sequencer #({vn}_seq_item#(DATA_WIDTH, ADDR_WIDTH));\n\n"
        f"  `uvm_component_param_utils({vn}_sequencer#(DATA_WIDTH, ADDR_WIDTH))\n\n"
        f"  // Accessible from sequences via p_sequencer\n"
        f"  virtual {vn}_if #(DATA_WIDTH, ADDR_WIDTH) vif;\n"
        f"  {vn}_cfg cfg;\n\n"
        f"  function new(string name, uvm_component parent);\n"
        f"    super.new(name, parent);\n"
        f"  endfunction\n\n"
        f"  function void build_phase(uvm_phase phase);\n"
        f"    super.build_phase(phase);\n"
        f"    if (!uvm_config_db #(virtual {vn}_if#(DATA_WIDTH,ADDR_WIDTH))\n"
        f"        ::get(this, \"\", \"vif\", vif))\n"
        f"      `uvm_fatal(\"NO_VIF\", {{\"vif not found for \", get_full_name()}})\n"
        f"    if (!uvm_config_db #({vn}_cfg)::get(this, \"\", \"cfg\", cfg))\n"
        f"      `uvm_fatal(\"NO_CFG\", {{\"cfg not found for \", get_full_name()}})\n"
        f"  endfunction\n"
        f"endclass\n"
    )
    safe_write(dv_root / "agents" / vn / f"{vn}_sequencer.sv", content)


def gen_coverage(vip: dict, dv_root: Path) -> None:
    vn = vip["vip_name"]
    p  = vip["parameters"]
    dw = p.get("DATA_WIDTH", 32)
    aw = p.get("ADDR_WIDTH", 32)

    content = (
        header(vn, "Functional Coverage", vip["protocol"], p) +
        f"class {vn}_coverage #(\n"
        f"  parameter int DATA_WIDTH = {dw},\n"
        f"  parameter int ADDR_WIDTH = {aw}\n"
        f") extends uvm_subscriber #({vn}_seq_item#(DATA_WIDTH, ADDR_WIDTH));\n\n"
        f"  `uvm_component_param_utils({vn}_coverage#(DATA_WIDTH, ADDR_WIDTH))\n\n"
        f"  typedef {vn}_seq_item #(DATA_WIDTH, ADDR_WIDTH) seq_item_t;\n"
        f"  seq_item_t trans;\n\n"
        f"  covergroup cg_{vn}_kind;\n"
        f"    cp_kind: coverpoint trans.kind {{\n"
        f"      // TODO: add bins per {vn}_kind_e value\n"
        f"    }}\n"
        f"  endgroup\n\n"
        f"  covergroup cg_{vn}_pkt_size;\n"
        f"    cp_pkt_size: coverpoint trans.pkt_size {{\n"
        f"      bins single  = {{1}};\n"
        f"      bins small   = {{[2:4]}};\n"
        f"      bins medium  = {{[5:8]}};\n"
        f"      bins large   = {{[9:16]}};\n"
        f"    }}\n"
        f"  endgroup\n\n"
        f"  covergroup cg_{vn}_delay;\n"
        f"    cp_delay: coverpoint trans.delay_type;\n"
        f"  endgroup\n\n"
        f"  // TODO: add protocol-specific covergroups from S2 testplan\n\n"
        f"  function new(string name, uvm_component parent);\n"
        f"    super.new(name, parent);\n"
        f"    cg_{vn}_kind     = new();\n"
        f"    cg_{vn}_pkt_size = new();\n"
        f"    cg_{vn}_delay    = new();\n"
        f"  endfunction\n\n"
        f"  virtual function void write(seq_item_t t);\n"
        f"    trans = t;\n"
        f"    cg_{vn}_kind.sample();\n"
        f"    cg_{vn}_pkt_size.sample();\n"
        f"    cg_{vn}_delay.sample();\n"
        f"  endfunction\n"
        f"endclass\n"
    )
    safe_write(dv_root / "agents" / vn / f"{vn}_coverage.sv", content)


def gen_agent(vip: dict, dv_root: Path) -> None:
    vn = vip["vip_name"]
    p  = vip["parameters"]
    dw = p.get("DATA_WIDTH", 32)
    aw = p.get("ADDR_WIDTH", 32)

    content = (
        header(vn, "Agent", vip["protocol"], p) +
        f"class {vn}_agent #(\n"
        f"  parameter int DATA_WIDTH = {dw},\n"
        f"  parameter int ADDR_WIDTH = {aw}\n"
        f") extends uvm_agent;\n\n"
        f"  `uvm_component_param_utils({vn}_agent#(DATA_WIDTH, ADDR_WIDTH))\n\n"
        f"  {vn}_driver    #(DATA_WIDTH, ADDR_WIDTH) m_driver;\n"
        f"  {vn}_monitor   #(DATA_WIDTH, ADDR_WIDTH) m_monitor;\n"
        f"  {vn}_sequencer #(DATA_WIDTH, ADDR_WIDTH) m_sequencer;\n"
        f"  {vn}_coverage  #(DATA_WIDTH, ADDR_WIDTH) m_coverage;\n"
        f"  {vn}_cfg cfg;\n"
        f"  uvm_analysis_port #({vn}_seq_item#(DATA_WIDTH, ADDR_WIDTH)) ap;\n\n"
        f"  function new(string name, uvm_component parent);\n"
        f"    super.new(name, parent);\n"
        f"  endfunction\n\n"
        f"  function void build_phase(uvm_phase phase);\n"
        f"    super.build_phase(phase);\n"
        f"    if (!uvm_config_db #({vn}_cfg)::get(this, \"\", \"cfg\", cfg)) begin\n"
        f"      cfg = {vn}_cfg::type_id::create(\"cfg\");\n"
        f"      `uvm_warning(\"NO_CFG\", \"Using default {vn}_cfg\")\n"
        f"    end\n"
        f"    m_monitor  = {vn}_monitor #(DATA_WIDTH, ADDR_WIDTH)"
        f"::type_id::create(\"m_monitor\",  this);\n"
        f"    m_coverage = {vn}_coverage #(DATA_WIDTH, ADDR_WIDTH)"
        f"::type_id::create(\"m_coverage\", this);\n"
        f"    if (cfg.is_active == UVM_ACTIVE) begin\n"
        f"      m_driver    = {vn}_driver    #(DATA_WIDTH, ADDR_WIDTH)"
        f"::type_id::create(\"m_driver\",    this);\n"
        f"      m_sequencer = {vn}_sequencer #(DATA_WIDTH, ADDR_WIDTH)"
        f"::type_id::create(\"m_sequencer\", this);\n"
        f"    end\n"
        f"  endfunction\n\n"
        f"  function void connect_phase(uvm_phase phase);\n"
        f"    if (cfg.is_active == UVM_ACTIVE)\n"
        f"      m_driver.seq_item_port.connect(m_sequencer.seq_item_export);\n"
        f"    m_monitor.ap.connect(m_coverage.analysis_export);\n"
        f"    ap = m_monitor.ap;\n"
        f"  endfunction\n"
        f"endclass\n"
    )
    safe_write(dv_root / "agents" / vn / f"{vn}_agent.sv", content)


def gen_base_seq(vip: dict, dv_root: Path) -> None:
    vn = vip["vip_name"]
    p  = vip["parameters"]
    dw = p.get("DATA_WIDTH", 32)
    aw = p.get("ADDR_WIDTH", 32)

    content = (
        header(vn, "Base Sequence", vip["protocol"], p) +
        f"class {vn}_base_seq #(\n"
        f"  parameter int DATA_WIDTH = {dw},\n"
        f"  parameter int ADDR_WIDTH = {aw}\n"
        f") extends uvm_sequence #({vn}_seq_item#(DATA_WIDTH, ADDR_WIDTH));\n\n"
        f"  `uvm_object_param_utils({vn}_base_seq#(DATA_WIDTH, ADDR_WIDTH))\n"
        f"  `uvm_declare_p_sequencer({vn}_sequencer#(DATA_WIDTH, ADDR_WIDTH))\n\n"
        f"  typedef {vn}_seq_item #(DATA_WIDTH, ADDR_WIDTH) seq_item_t;\n\n"
        f"  function new(string name = \"{vn}_base_seq\");\n"
        f"    super.new(name);\n"
        f"  endfunction\n\n"
        f"  task send(seq_item_t item);\n"
        f"    start_item(item);\n"
        f"    if (!item.randomize()) `uvm_fatal(\"RAND_FAIL\", \"randomize() failed\")\n"
        f"    finish_item(item);\n"
        f"  endtask\n\n"
        f"  task wait_clk(int unsigned n = 1);\n"
        f"    repeat(n) @(posedge p_sequencer.vif.clk);\n"
        f"  endtask\n\n"
        f"  virtual task body();\n"
        f"    // Override in derived sequences\n"
        f"  endtask\n"
        f"endclass\n"
    )
    safe_write(dv_root / "agents" / vn / f"{vn}_base_seq.sv", content)


def gen_reset_seq(vip: dict, dv_root: Path) -> None:
    vn = vip["vip_name"]
    p  = vip["parameters"]
    dw = p.get("DATA_WIDTH", 32)
    aw = p.get("ADDR_WIDTH", 32)

    content = (
        header(vn, "Reset Sequence", vip["protocol"], p) +
        f"class {vn}_reset_seq #(\n"
        f"  parameter int DATA_WIDTH = {dw},\n"
        f"  parameter int ADDR_WIDTH = {aw}\n"
        f") extends {vn}_base_seq #(DATA_WIDTH, ADDR_WIDTH);\n\n"
        f"  `uvm_object_param_utils({vn}_reset_seq#(DATA_WIDTH, ADDR_WIDTH))\n\n"
        f"  function new(string name = \"{vn}_reset_seq\");\n"
        f"    super.new(name);\n"
        f"  endfunction\n\n"
        f"  virtual task body();\n"
        f"    // TODO: drive {vip['protocol']} protocol idle/reset state\n"
        f"    // Deassert valid signals, drive address/data to 0, etc.\n"
        f"    @(posedge p_sequencer.vif.clk iff p_sequencer.vif.rst_n);\n"
        f"    `uvm_info(get_type_name(), \"{vip['protocol']} reset done — interface idle\", UVM_MEDIUM)\n"
        f"  endtask\n"
        f"endclass\n"
    )
    safe_write(dv_root / "agents" / vn / f"{vn}_reset_seq.sv", content)


def gen_pkg(vip: dict, dv_root: Path) -> None:
    vn = vip["vip_name"]
    p  = vip["parameters"]

    content = (
        header(vn, "Agent Package", vip["protocol"], p) +
        f"// Include BEFORE any file that references {vn}_*\n"
        f"package {vn}_agent_pkg;\n"
        f"  import uvm_pkg::*;\n"
        f"  `include \"uvm_macros.svh\"\n\n"
        f"  typedef enum logic [1:0] {{\n"
        f"    {vn.upper()}_READ  = 2'b00,\n"
        f"    {vn.upper()}_WRITE = 2'b01\n"
        f"    // TODO: add protocol-specific transaction kinds\n"
        f"  }} {vn}_kind_e;\n\n"
        f"  typedef enum logic [1:0] {{\n"
        f"    ZERO   = 2'b00,\n"
        f"    FIXED  = 2'b01,\n"
        f"    RANDOM = 2'b10\n"
        f"  }} delay_type_e;\n\n"
        f"  `include \"{vn}_cfg.sv\"\n"
        f"  `include \"{vn}_seq_item.sv\"\n"
        f"  `include \"{vn}_sequencer.sv\"\n"
        f"  `include \"{vn}_driver.sv\"\n"
        f"  `include \"{vn}_monitor.sv\"\n"
        f"  `include \"{vn}_coverage.sv\"\n"
        f"  `include \"{vn}_agent.sv\"\n"
        f"  `include \"{vn}_base_seq.sv\"\n"
        f"  `include \"{vn}_reset_seq.sv\"\n"
        f"  // TODO: add protocol-specific sequences here\n"
        f"endpackage : {vn}_agent_pkg\n"
    )
    safe_write(dv_root / "agents" / vn / f"{vn}_agent_pkg.sv", content)


# ── RAL Generators ─────────────────────────────────────────────────────────────

def gen_ral(cfg_data: dict, dv_root: Path) -> None:
    proj     = cfg_data["project_name"]
    reg_map  = cfg_data.get("register_map", {})
    regs     = reg_map.get("registers", [])
    bus_vip  = reg_map.get("bus_vip", "ahb_vip")
    base_addr = reg_map.get("base_addr", "0x0")

    if not regs:
        print("  INFO: No registers found — skipping RAL generation")
        return

    ral_dir = dv_root / "ral"

    # Per-register files
    for reg in regs:
        _gen_reg_file(proj, reg, ral_dir)

    # Register block
    _gen_reg_block(proj, regs, base_addr, ral_dir)

    # RAL adapter
    _gen_ral_adapter(bus_vip, ral_dir)

    # RAL package
    reg_names = [r["name"].lower() for r in regs]
    pkg_content = (
        f"// {proj.upper()} RAL Package — generated by dv-tb-scaffold (S5)\n"
        f"package {proj}_ral_pkg;\n"
        f"  import uvm_pkg::*;\n"
        f"  `include \"uvm_macros.svh\"\n\n"
    )
    for rn in reg_names:
        pkg_content += f"  `include \"{proj}_{rn}_reg.sv\"\n"
    pkg_content += (
        f"  `include \"{proj}_reg_block.sv\"\n"
        f"  `include \"{bus_vip}_ral_adapter.sv\"\n"
        f"endpackage : {proj}_ral_pkg\n"
    )
    safe_write(ral_dir / f"{proj}_ral_pkg.sv", pkg_content)


def _gen_reg_file(proj: str, reg: dict, ral_dir: Path) -> None:
    rn     = reg["name"].lower()
    rname  = reg["name"]
    offset = reg.get("offset", "0x00")
    reset  = reg.get("reset_value", "0x00000000")
    desc   = reg.get("description", "")
    fields = reg.get("fields", [])

    field_decl = "\n".join(f"  rand uvm_reg_field {f['name']};" for f in fields)
    field_cfg  = ""
    for f in fields:
        bits  = f.get("width", 1)
        lsb   = _lsb_from_bits(f.get("bits", "[0:0]"))
        acc   = f.get("access", "RW")
        rst   = f.get("reset_value", "0x0")
        field_cfg += (
            f"    {f['name']} = uvm_reg_field::type_id::create(\"{f['name']}\");\n"
            f"    {f['name']}.configure(\n"
            f"      .parent(this), .size({bits}), .lsb_pos({lsb}),\n"
            f"      .access(\"{acc}\"), .volatile(1'b0), .reset({rst}),\n"
            f"      .has_reset(1'b1), .is_rand(1'b1),\n"
            f"      .individually_accessible(1'b0));\n"
        )

    content = (
        f"// {rname} Register — generated by dv-tb-scaffold (S5)\n"
        f"// Offset: {offset}  Reset: {reset}\n"
        f"// {desc}\n\n"
        f"class {proj}_{rn}_reg extends uvm_reg;\n"
        f"  `uvm_object_utils({proj}_{rn}_reg)\n\n"
        f"{field_decl}\n\n"
        f"  function new(string name = \"{proj}_{rn}_reg\");\n"
        f"    super.new(name, 32, UVM_NO_COVERAGE);\n"
        f"  endfunction\n\n"
        f"  virtual function void build();\n"
        f"{field_cfg}"
        f"  endfunction\n"
        f"endclass\n"
    )
    safe_write(ral_dir / f"{proj}_{rn}_reg.sv", content)


def _lsb_from_bits(bits_str: str) -> int:
    """Parse '[MSB:LSB]' or '[N]' → LSB."""
    import re
    m = re.search(r'\[(\d+):(\d+)\]', bits_str)
    if m:
        return int(m.group(2))
    m = re.search(r'\[(\d+)\]', bits_str)
    if m:
        return int(m.group(1))
    return 0


def _gen_reg_block(proj: str, regs: list, base_addr: str, ral_dir: Path) -> None:
    reg_handles = "\n".join(
        f"  rand {proj}_{r['name'].lower()}_reg {r['name'].lower()};" for r in regs
    )
    reg_create = ""
    for r in regs:
        rn = r["name"].lower()
        reg_create += (
            f"    {rn} = {proj}_{rn}_reg::type_id::create(\"{rn}\");\n"
            f"    {rn}.configure(.blk_parent(this), .hdl_path(\"{rn}\"));\n"
            f"    {rn}.build();\n"
        )
    reg_add = "\n".join(
        f"    m_map.add_reg({r['name'].lower()}, {r.get('offset','0x00')}, \"RW\");"
        for r in regs
    )
    backdoor = "\n".join(
        f"    {r['name'].lower()}.add_hdl_path_slice(\n"
        f"      $sformatf(\"%s.{r['name'].lower()}\", dut_path), 0, 32);"
        for r in regs
    )

    content = (
        f"// {proj.upper()} Register Block — generated by dv-tb-scaffold (S5)\n"
        f"class {proj}_reg_block extends uvm_reg_block;\n"
        f"  `uvm_object_utils({proj}_reg_block)\n\n"
        f"{reg_handles}\n\n"
        f"  uvm_reg_map m_map;\n\n"
        f"  function new(string name = \"{proj}_reg_block\");\n"
        f"    super.new(name, UVM_NO_COVERAGE);\n"
        f"  endfunction\n\n"
        f"  virtual function void build();\n"
        f"{reg_create}\n"
        f"    m_map = create_map(\"m_map\", {base_addr}, 4, UVM_LITTLE_ENDIAN);\n"
        f"{reg_add}\n"
        f"    lock_model();\n"
        f"  endfunction\n\n"
        f"  // ── Backdoor Access ────────────────────────────────────────────\n"
        f"  // Call from test: m_reg_block.configure_backdoor(\"tb_top.u_dut\");\n"
        f"  virtual function void configure_backdoor(string dut_path);\n"
        f"{backdoor}\n"
        f"  endfunction\n"
        f"endclass\n"
    )
    safe_write(ral_dir / f"{proj}_reg_block.sv", content)


def _gen_ral_adapter(bus_vip: str, ral_dir: Path) -> None:
    vn  = bus_vip
    VN  = vn.upper()

    content = (
        f"// {vn.upper()} RAL Adapter — generated by dv-tb-scaffold (S5)\n"
        f"class {vn}_ral_adapter extends uvm_reg_adapter;\n"
        f"  `uvm_object_utils({vn}_ral_adapter)\n\n"
        f"  function new(string name = \"{vn}_ral_adapter\");\n"
        f"    super.new(name);\n"
        f"    supports_byte_enable = 0;\n"
        f"    provides_responses   = 1;\n"
        f"  endfunction\n\n"
        f"  virtual function uvm_sequence_item reg2bus(const ref uvm_reg_bus_op rw);\n"
        f"    {vn}_seq_item item = {vn}_seq_item::type_id::create(\"item\");\n"
        f"    item.addr = rw.addr;\n"
        f"    item.data = rw.data;\n"
        f"    item.kind = (rw.kind == UVM_READ) ? {VN}_READ : {VN}_WRITE;\n"
        f"    return item;\n"
        f"  endfunction\n\n"
        f"  virtual function void bus2reg(uvm_sequence_item bus_item,\n"
        f"                               ref uvm_reg_bus_op rw);\n"
        f"    {vn}_seq_item item;\n"
        f"    if (!$cast(item, bus_item))\n"
        f"      `uvm_fatal(\"CAST\", \"bus2reg: cast to {vn}_seq_item failed\")\n"
        f"    rw.addr   = item.addr;\n"
        f"    rw.data   = item.data;\n"
        f"    rw.kind   = (item.kind == {VN}_READ) ? UVM_READ : UVM_WRITE;\n"
        f"    rw.status = UVM_IS_OK;\n"
        f"  endfunction\n"
        f"endclass\n"
    )
    safe_write(ral_dir / f"{vn}_ral_adapter.sv", content)


# ── Environment Generators ─────────────────────────────────────────────────────

def gen_env_cfg(cfg_data: dict, dv_root: Path) -> None:
    proj = cfg_data["project_name"]
    vips = cfg_data.get("unique_vips", [])

    cfg_fields  = ""
    cfg_creates = ""
    for v in vips:
        for inst in v.get("instances", []):
            fn = inst["if_name"]
            cfg_fields  += f"  {v['vip_name']}_cfg m_{fn}_cfg;\n"
            cfg_creates += f"    m_{fn}_cfg = {v['vip_name']}_cfg::type_id::create(\"m_{fn}_cfg\");\n"

    content = (
        f"// {proj.upper()} Environment Config — generated by dv-tb-scaffold (S5)\n"
        f"class {proj}_env_cfg extends uvm_object;\n"
        f"  `uvm_object_utils({proj}_env_cfg)\n\n"
        f"  // ── Per-agent config (one per interface instance) ────────────────\n"
        f"{cfg_fields}\n"
        f"  // ── RAL handle (set after reg_block.build()) ─────────────────────\n"
        f"  {proj}_reg_block m_reg_block;\n\n"
        f"  function new(string name = \"{proj}_env_cfg\");\n"
        f"    super.new(name);\n"
        f"{cfg_creates}"
        f"  endfunction\n"
        f"endclass\n"
    )
    safe_write(dv_root / "env" / f"{proj}_env_cfg.sv", content)


def gen_ref_model(cfg_data: dict, dv_root: Path) -> None:
    proj      = cfg_data["project_name"]
    ref_model = cfg_data.get("ref_model", {})
    vips      = cfg_data.get("unique_vips", [])

    # Find first input vip (non-register)
    reg_vip = cfg_data.get("register_map", {}).get("bus_vip", "")
    input_vip = next(
        (v for v in vips if v["vip_name"] != reg_vip), vips[0] if vips else None
    )
    output_vip = vips[-1] if vips else None

    iv  = input_vip["vip_name"]  if input_vip  else "input_vip"
    ov  = output_vip["vip_name"] if output_vip else "output_vip"
    idw = input_vip["parameters"].get("DATA_WIDTH", 32)  if input_vip  else 32
    odw = output_vip["parameters"].get("DATA_WIDTH", 32) if output_vip else 32

    content = (
        f"// {proj.upper()} Reference Model — generated by dv-tb-scaffold (S5)\n"
        f"// Receives stimulus from input agents, predicts expected DUT output.\n"
        f"// IMPORTANT: implement the predict() logic in write_input() below.\n\n"
        f"`uvm_analysis_imp_decl(_input)\n"
        f"`uvm_analysis_imp_decl(_reg)\n\n"
        f"class {proj}_ref_model extends uvm_component;\n"
        f"  `uvm_component_utils({proj}_ref_model)\n\n"
        f"  // Input from input monitor\n"
        f"  uvm_analysis_imp_input #({iv}_seq_item#({idw}), {proj}_ref_model) m_input_imp;\n"
        f"  // Input from register monitor (RAL updates)\n"
        f"  uvm_analysis_imp_reg #({reg_vip}_seq_item, {proj}_ref_model) m_reg_imp;\n"
        f"  // Prediction output → scoreboard\n"
        f"  uvm_analysis_port #({ov}_seq_item#({odw})) ap_out;\n\n"
        f"  // Internal state (config shadow)\n"
        f"  // TODO: add fields mirroring DUT internal state\n\n"
        f"  function new(string name, uvm_component parent);\n"
        f"    super.new(name, parent);\n"
        f"    m_input_imp = new(\"m_input_imp\", this);\n"
        f"    m_reg_imp   = new(\"m_reg_imp\",   this);\n"
        f"    ap_out      = new(\"ap_out\",       this);\n"
        f"  endfunction\n\n"
        f"  // Called when input stimulus arrives\n"
        f"  virtual function void write_input({iv}_seq_item#({idw}) stimulus);\n"
        f"    {ov}_seq_item#({odw}) predicted;\n"
        f"    predicted = {ov}_seq_item#({odw})::type_id::create(\"predicted\");\n"
        f"    // TODO: apply DUT transformation\n"
        f"    // predicted.data = transform(stimulus.data);\n"
        f"    `uvm_info(get_type_name(),\n"
        f"      $sformatf(\"Predicting output for: %s\", stimulus.convert2string()),\n"
        f"      UVM_HIGH)\n"
        f"    ap_out.write(predicted);\n"
        f"  endfunction\n\n"
        f"  // Called when register write completes — update internal config shadow\n"
        f"  virtual function void write_reg({reg_vip}_seq_item reg_item);\n"
        f"    // TODO: shadow register updates for accurate prediction\n"
        f"  endfunction\n"
        f"endclass\n"
    )
    safe_write(dv_root / "env" / f"{proj}_ref_model.sv", content)


def gen_scoreboard(cfg_data: dict, dv_root: Path) -> None:
    proj      = cfg_data["project_name"]
    vips      = cfg_data.get("unique_vips", [])
    reg_vip   = cfg_data.get("register_map", {}).get("bus_vip", "")
    output_vip = vips[-1] if vips else None
    ov  = output_vip["vip_name"] if output_vip else "output_vip"
    odw = output_vip["parameters"].get("DATA_WIDTH", 32) if output_vip else 32

    content = (
        f"// {proj.upper()} Scoreboard — generated by dv-tb-scaffold (S5)\n"
        f"`uvm_analysis_imp_decl(_exp)\n"
        f"`uvm_analysis_imp_decl(_act)\n\n"
        f"class {proj}_scoreboard extends uvm_scoreboard;\n"
        f"  `uvm_component_utils({proj}_scoreboard)\n\n"
        f"  {ov}_seq_item#({odw}) m_expected_q[$];\n"
        f"  uvm_analysis_imp_exp #({ov}_seq_item#({odw}), {proj}_scoreboard) m_exp_imp;\n"
        f"  uvm_analysis_imp_act #({ov}_seq_item#({odw}), {proj}_scoreboard) m_act_imp;\n\n"
        f"  int unsigned m_pass_cnt = 0;\n"
        f"  int unsigned m_fail_cnt = 0;\n\n"
        f"  function new(string name, uvm_component parent);\n"
        f"    super.new(name, parent);\n"
        f"    m_exp_imp = new(\"m_exp_imp\", this);\n"
        f"    m_act_imp = new(\"m_act_imp\", this);\n"
        f"  endfunction\n\n"
        f"  virtual function void write_exp({ov}_seq_item#({odw}) item);\n"
        f"    m_expected_q.push_back(item);\n"
        f"  endfunction\n\n"
        f"  virtual function void write_act({ov}_seq_item#({odw}) actual);\n"
        f"    {ov}_seq_item#({odw}) expected;\n"
        f"    if (m_expected_q.size() == 0) begin\n"
        f"      m_fail_cnt++;\n"
        f"      `uvm_error(\"SB_UNEXPECTED\",\n"
        f"        $sformatf(\"Unexpected: %s\", actual.convert2string()))\n"
        f"      return;\n"
        f"    end\n"
        f"    expected = m_expected_q.pop_front();\n"
        f"    if (actual.data !== expected.data) begin\n"
        f"      m_fail_cnt++;\n"
        f"      `uvm_error(\"SB_MISMATCH\",\n"
        f"        $sformatf(\"MISMATCH: exp=0x%0h act=0x%0h\",\n"
        f"                  expected.data, actual.data))\n"
        f"    end else begin\n"
        f"      m_pass_cnt++;\n"
        f"    end\n"
        f"    // TODO: add per-checker procedural checks from testplan (Col 8 Procedural)\n"
        f"  endfunction\n\n"
        f"  function void check_phase(uvm_phase phase);\n"
        f"    if (m_expected_q.size() > 0)\n"
        f"      `uvm_error(\"SB_LEFTOVER\",\n"
        f"        $sformatf(\"%0d expected never matched\", m_expected_q.size()))\n"
        f"    `uvm_info(\"SB\",\n"
        f"      $sformatf(\"PASS=%0d FAIL=%0d\", m_pass_cnt, m_fail_cnt), UVM_NONE)\n"
        f"  endfunction\n"
        f"endclass\n"
    )
    safe_write(dv_root / "env" / f"{proj}_scoreboard.sv", content)


def gen_env(cfg_data: dict, dv_root: Path) -> None:
    proj    = cfg_data["project_name"]
    vips    = cfg_data.get("unique_vips", [])
    reg_map = cfg_data.get("register_map", {})
    reg_vip = reg_map.get("bus_vip", "")
    reg_if  = reg_map.get("bus_if", "")

    agent_decl    = ""
    agent_create  = ""
    agent_connect = ""
    vseqr_wires   = ""

    for v in vips:
        vn  = v["vip_name"]
        dw  = v["parameters"].get("DATA_WIDTH", 32)
        for inst in v.get("instances", []):
            fn = inst["if_name"]
            agent_decl    += f"  {vn}_agent #(.DATA_WIDTH({dw})) m_{fn}_agent;\n"
            agent_create  += (
                f"    m_{fn}_agent = {vn}_agent#({dw})::type_id::create(\"m_{fn}_agent\", this);\n"
                f"    uvm_config_db #({vn}_cfg)::set(this, \"m_{fn}_agent.*\", \"cfg\", cfg.m_{fn}_cfg);\n"
            )
            agent_connect += (
                f"    // TODO: connect m_{fn}_agent.ap → scoreboard / ref model as appropriate\n"
            )
            vseqr_wires   += f"    m_vseqr.m_{fn}_seqr = m_{fn}_agent.m_sequencer;\n"

    ral_section = ""
    if reg_vip and reg_map.get("registers"):
        ral_section = (
            f"\n    // Build RAL\n"
            f"    m_reg_block     = {proj}_reg_block::type_id::create(\"m_reg_block\");\n"
            f"    m_reg_block.build();\n"
            f"    m_ral_adapter   = {reg_vip}_ral_adapter::type_id::create(\"m_ral_adapter\",  this);\n"
            f"    m_reg_predictor = uvm_reg_predictor#({reg_vip}_seq_item)\n"
            f"                      ::type_id::create(\"m_reg_predictor\", this);\n"
            f"    cfg.m_reg_block = m_reg_block;\n"
        )
        ral_connect = (
            f"\n    // Connect RAL\n"
            f"    m_reg_block.m_map.set_sequencer(\n"
            f"      m_{reg_if}_agent.m_sequencer, m_ral_adapter);\n"
            f"    m_reg_predictor.map     = m_reg_block.m_map;\n"
            f"    m_reg_predictor.adapter = m_ral_adapter;\n"
            f"    m_{reg_if}_agent.m_monitor.ap.connect(m_reg_predictor.bus_in);\n"
        )
    else:
        ral_connect = ""

    ral_decl = ""
    if reg_vip:
        ral_decl = (
            f"  {proj}_reg_block   m_reg_block;\n"
            f"  {reg_vip}_ral_adapter m_ral_adapter;\n"
            f"  uvm_reg_predictor #({reg_vip}_seq_item) m_reg_predictor;\n"
        )

    content = (
        f"// {proj.upper()} UVM Environment — generated by dv-tb-scaffold (S5)\n"
        f"class {proj}_env extends uvm_env;\n"
        f"  `uvm_component_utils({proj}_env)\n\n"
        f"  // ── Agents ─────────────────────────────────────────────────────────\n"
        f"{agent_decl}\n"
        f"  // ── Environment components ─────────────────────────────────────────\n"
        f"  {proj}_scoreboard  m_scoreboard;\n"
        f"  {proj}_ref_model   m_ref_model;\n"
        f"  {proj}_virtual_seqr m_vseqr;\n"
        f"  {proj}_env_cfg     cfg;\n\n"
        f"  // ── RAL ────────────────────────────────────────────────────────────\n"
        f"{ral_decl}\n"
        f"  function new(string name, uvm_component parent);\n"
        f"    super.new(name, parent);\n"
        f"  endfunction\n\n"
        f"  function void build_phase(uvm_phase phase);\n"
        f"    super.build_phase(phase);\n"
        f"    if (!uvm_config_db #({proj}_env_cfg)::get(this, \"\", \"cfg\", cfg))\n"
        f"      `uvm_fatal(\"NO_CFG\", \"env cfg not found in config_db\")\n"
        f"{agent_create}\n"
        f"    m_scoreboard = {proj}_scoreboard::type_id::create(\"m_scoreboard\", this);\n"
        f"    m_ref_model  = {proj}_ref_model::type_id::create(\"m_ref_model\",  this);\n"
        f"    m_vseqr      = {proj}_virtual_seqr::type_id::create(\"m_vseqr\",   this);\n"
        f"{ral_section}"
        f"  endfunction\n\n"
        f"  function void connect_phase(uvm_phase phase);\n"
        f"{ral_connect}"
        f"{agent_connect}\n"
        f"    // TODO: connect ref model inputs/outputs to monitors/scoreboard\n"
        f"{vseqr_wires}"
        f"  endfunction\n"
        f"endclass\n"
    )
    safe_write(dv_root / "env" / f"{proj}_env.sv", content)


def gen_virtual_seqr(cfg_data: dict, dv_root: Path) -> None:
    proj = cfg_data["project_name"]
    vips = cfg_data.get("unique_vips", [])

    seqr_handles = ""
    for v in vips:
        vn = v["vip_name"]
        dw = v["parameters"].get("DATA_WIDTH", 32)
        for inst in v.get("instances", []):
            fn = inst["if_name"]
            seqr_handles += f"  {vn}_sequencer #(.DATA_WIDTH({dw})) m_{fn}_seqr;\n"

    content = (
        f"// {proj.upper()} Virtual Sequencer — generated by dv-tb-scaffold (S5)\n"
        f"class {proj}_virtual_seqr extends uvm_sequencer;\n"
        f"  `uvm_component_utils({proj}_virtual_seqr)\n\n"
        f"  // ── Agent sequencer handles ───────────────────────────────────────\n"
        f"{seqr_handles}\n"
        f"  function new(string name, uvm_component parent);\n"
        f"    super.new(name, parent);\n"
        f"  endfunction\n"
        f"endclass\n"
    )
    safe_write(dv_root / "seq_lib" / f"{proj}_virtual_seqr.sv", content)


def gen_tb_top(cfg_data: dict, dv_root: Path) -> None:
    proj    = cfg_data["project_name"]
    vips    = cfg_data.get("unique_vips", [])

    if_inst = ""
    cfg_db  = ""
    dut_ports = ""
    imports = ""

    for v in vips:
        vn = v["vip_name"]
        dw = v["parameters"].get("DATA_WIDTH", 32)
        aw = v["parameters"].get("ADDR_WIDTH", 32)
        imports += f"  import {vn}_agent_pkg::*;\n"
        for inst in v.get("instances", []):
            fn = inst["if_name"]
            if_inst  += f"  {vn}_if #(.DATA_WIDTH({dw}), .ADDR_WIDTH({aw})) u_{fn} (.clk(clk), .rst_n(rst_n));\n"
            cfg_db   += (
                f"    uvm_config_db #(virtual {vn}_if#({dw},{aw}))\n"
                f"      ::set(null, \"uvm_test_top.m_env.m_{fn}_agent.*\", \"vif\", u_{fn});\n"
            )
            dut_ports += f"    // .port (u_{fn}.signal),  // TODO: connect {fn}\n"

    content = (
        f"// {proj.upper()} Testbench Top — generated by dv-tb-scaffold (S5)\n"
        f"module {proj}_tb_top;\n"
        f"  import uvm_pkg::*;\n"
        f"  `include \"uvm_macros.svh\"\n"
        f"  import {proj}_env_pkg::*;\n"
        f"  import {proj}_ral_pkg::*;\n"
        f"{imports}\n"
        f"  parameter realtime CLK_PERIOD = 10ns;  // 100 MHz — adjust to match DUT spec\n\n"
        f"  logic clk;\n"
        f"  logic rst_n;\n\n"
        f"  initial clk = 0;\n"
        f"  always #(CLK_PERIOD/2) clk = ~clk;\n\n"
        f"  initial begin\n"
        f"    rst_n = 0;\n"
        f"    repeat(10) @(posedge clk);\n"
        f"    rst_n = 1;\n"
        f"    `uvm_info(\"TB_TOP\", \"Reset deasserted\", UVM_NONE)\n"
        f"  end\n\n"
        f"  // ── Interface Instances ────────────────────────────────────────────\n"
        f"{if_inst}\n"
        f"  // ── DUT Instance ──────────────────────────────────────────────────\n"
        f"  {proj}_dut u_dut (\n"
        f"    .clk   (clk),\n"
        f"    .rst_n (rst_n)\n"
        f"{dut_ports}"
        f"  );\n\n"
        f"  // ── UVM Config DB ─────────────────────────────────────────────────\n"
        f"  initial begin\n"
        f"{cfg_db}"
        f"    run_test();  // +UVM_TESTNAME on command line\n"
        f"  end\n\n"
        f"  // ── Backdoor path setup ───────────────────────────────────────────\n"
        f"  // initial env.m_reg_block.configure_backdoor(\"tb_top.u_dut\");\n\n"
        f"endmodule : {proj}_tb_top\n"
    )
    safe_write(dv_root / "tb" / f"{proj}_tb_top.sv", content)


def gen_dut_stub(cfg_data: dict, dv_root: Path) -> None:
    proj = cfg_data["project_name"]
    vips = cfg_data.get("unique_vips", [])

    port_comments = ""
    for v in vips:
        proto = v["protocol"]
        for inst in v.get("instances", []):
            fn   = inst["if_name"]
            role = inst.get("role", "slave")
            port_comments += f"  // TODO: add {proto} ({fn}) ports — role: {role}\n"

    content = (
        f"// {proj.upper()} DUT Stub — generated by dv-tb-scaffold (S5)\n"
        f"// Synthesizable port-list shell. Replace with real RTL.\n"
        f"// Outputs driven to known values to prevent X-propagation.\n\n"
        f"module {proj}_dut (\n"
        f"  input  logic clk,\n"
        f"  input  logic rst_n\n"
        f"  // TODO: add DUT ports derived from interface list\n"
        f"{port_comments}"
        f");\n\n"
        f"  // TODO: replace stub with real RTL implementation\n"
        f"  // All outputs should be assigned to safe zero/known values:\n"
        f"  // assign <output_port> = '0;\n\n"
        f"endmodule : {proj}_dut\n"
    )
    safe_write(dv_root / "tb" / f"{proj}_dut_stub.sv", content)


def gen_env_pkg(cfg_data: dict, dv_root: Path) -> None:
    proj = cfg_data["project_name"]
    vips = cfg_data.get("unique_vips", [])

    imports = "".join(f"  import {v['vip_name']}_agent_pkg::*;\n" for v in vips)

    content = (
        f"// {proj.upper()} Environment Package — generated by dv-tb-scaffold (S5)\n"
        f"package {proj}_env_pkg;\n"
        f"  import uvm_pkg::*;\n"
        f"  `include \"uvm_macros.svh\"\n\n"
        f"  // Import all VIP packages\n"
        f"{imports}\n"
        f"  // Environment components (dependency order)\n"
        f"  `include \"{proj}_env_cfg.sv\"\n"
        f"  `include \"{proj}_ref_model.sv\"\n"
        f"  `include \"{proj}_scoreboard.sv\"\n"
        f"  `include \"{proj}_virtual_seqr.sv\"\n"
        f"  `include \"{proj}_env.sv\"\n"
        f"endpackage : {proj}_env_pkg\n"
    )
    safe_write(dv_root / "env" / f"{proj}_env_pkg.sv", content)


# ── Main ───────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(description="S5 TB Scaffold Generator")
    parser.add_argument("--config", required=True,
                        help="Path to tb_scaffold_data.json")
    parser.add_argument("--phase",
                        choices=["vips", "ral", "env", "all"],
                        default="all",
                        help="Which phase to generate (default: all)")
    args = parser.parse_args()

    cfg_path = Path(args.config)
    if not cfg_path.exists():
        print(f"ERROR: config file not found: {cfg_path}", file=sys.stderr)
        sys.exit(1)

    with cfg_path.open() as f:
        cfg_data = json.load(f)

    proj_root = Path(cfg_data.get("project_root", "."))
    dv_root   = proj_root / "dv"
    vips      = cfg_data.get("unique_vips", [])

    print("=" * 60)
    print(f"  DV TB Scaffold Generator — {cfg_data.get('project_name', 'unknown')}")
    print(f"  Phase  : {args.phase}")
    print(f"  DV Root: {dv_root}")
    print("=" * 60)

    if args.phase in ("vips", "all"):
        print("\n[VIPs]")
        for vip in vips:
            vn = vip["vip_name"]
            print(f"  Generating {vn} ({vip['protocol']})...")
            gen_interface(vip, dv_root)
            gen_seq_item(vip, dv_root)
            gen_cfg(vip, dv_root)
            gen_driver(vip, dv_root)
            gen_monitor(vip, dv_root)
            gen_sequencer(vip, dv_root)
            gen_coverage(vip, dv_root)
            gen_agent(vip, dv_root)
            gen_base_seq(vip, dv_root)
            gen_reset_seq(vip, dv_root)
            gen_pkg(vip, dv_root)

    if args.phase in ("ral", "all"):
        print("\n[RAL]")
        gen_ral(cfg_data, dv_root)

    if args.phase in ("env", "all"):
        print("\n[Environment]")
        gen_env_cfg(cfg_data, dv_root)
        gen_ref_model(cfg_data, dv_root)
        gen_scoreboard(cfg_data, dv_root)
        gen_env(cfg_data, dv_root)
        gen_virtual_seqr(cfg_data, dv_root)
        gen_tb_top(cfg_data, dv_root)
        gen_dut_stub(cfg_data, dv_root)
        gen_env_pkg(cfg_data, dv_root)

    print("\n" + "=" * 60)
    print("  Generation complete.")
    print("  All generated files use safe_write() — existing files NOT overwritten.")
    print("=" * 60)


if __name__ == "__main__":
    main()
