#!/usr/bin/env python3
"""
generate_testplan_excel.py
DV Testplan Excel generator — used by dv-testplan skill (S2)

Usage:
    python3 generate_testplan_excel.py \
        --data /tmp/<project>_testplan_data.json \
        --output <output_dir>/testplan.xlsx \
        --project <project_name>
"""

import argparse
import json
import sys
from pathlib import Path
from datetime import date

try:
    import openpyxl
    from openpyxl.styles import (
        Font, PatternFill, Alignment, Border, Side, GradientFill
    )
    from openpyxl.utils import get_column_letter
except ImportError:
    print("ERROR: openpyxl not installed. Run: pip3 install openpyxl")
    sys.exit(1)


# ── Colour palette ────────────────────────────────────────────────────────────
C_HEADER_BG   = "1A1A2E"   # dark navy
C_HEADER_FG   = "FFFFFF"
C_FEATURE_BG  = "16213E"   # slightly lighter navy
C_FEATURE_FG  = "FFFFFF"
C_DVI_BG      = "DBEAFE"   # light blue  — DV-I
C_DVC_BG      = "DCFCE7"   # light green — DV-C
C_DVF_BG      = "FEF9C3"   # light yellow — DV-F
C_NEG_BG      = "FEE2E2"   # light red   — [NEG]
C_STRESS_BG   = "FFF7ED"   # light orange — [STRESS]/[CORNER]
C_ALT_BG      = "F8FAFC"   # alternating row
C_WHITE       = "FFFFFF"
C_SUMMARY_HDR = "0F3460"
C_ACCENT      = "E94560"

MILESTONE_COLORS = {"DV-I": C_DVI_BG, "DV-C": C_DVC_BG, "DV-F": C_DVF_BG}

COLUMNS = [
    ("Feature",               28),
    ("Sub-feature",           28),
    ("Brief Description",     40),
    ("Verification Type",     36),
    ("Testcase Description",  55),
    ("Coverpoint Description",55),
    ("Checker ID",            32),
    ("Checker Type",          22),
    ("Assertion Code",        55),
    ("Milestone",             14),
    ("Parent Feature",        30),
]


def thin_border():
    s = Side(style="thin", color="CCCCCC")
    return Border(left=s, right=s, top=s, bottom=s)


def make_font(bold=False, color="000000", size=9):
    return Font(bold=bold, color=color, size=size, name="Calibri")


def make_fill(hex_color):
    return PatternFill("solid", fgColor=hex_color)


def wrap_align(horizontal="left", vertical="top"):
    return Alignment(wrap_text=True, horizontal=horizontal, vertical=vertical)


# ── Summary Sheet ─────────────────────────────────────────────────────────────
def build_summary_sheet(wb, data: dict, project: str):
    ws = wb.create_sheet("Summary", 0)
    ws.sheet_view.showGridLines = False
    ws.column_dimensions["A"].width = 38
    ws.column_dimensions["B"].width = 18

    rows = data.get("rows", [])
    today = date.today().isoformat()

    # Count stats
    total     = len(rows)
    directed  = sum(1 for r in rows if "Directed"  in r.get("verification_type",""))
    random_t  = sum(1 for r in rows if "Random"    in r.get("verification_type",""))
    cov_only  = sum(1 for r in rows if r.get("verification_type","").strip().startswith("Coverpoint") and "Testcase" not in r.get("verification_type",""))
    neg       = sum(1 for r in rows if str(r.get("subfeature","")).startswith("[NEG]"))
    stress    = sum(1 for r in rows if str(r.get("subfeature","")).startswith(("[STRESS]","[CORNER]")))

    dvi = sum(1 for r in rows if r.get("milestone") == "DV-I")
    dvc = sum(1 for r in rows if r.get("milestone") == "DV-C")
    dvf = sum(1 for r in rows if r.get("milestone") == "DV-F")

    cgs  = len(set(r.get("covergroup","") for r in rows if r.get("covergroup","")))
    cps  = sum(1 for r in rows if r.get("coverpoint_desc","").strip())
    xcps = sum(1 for r in rows if "cross" in r.get("coverpoint_desc","").lower())

    proc  = sum(1 for r in rows if r.get("checker_type","") == "Procedural")
    asr   = sum(1 for r in rows if r.get("checker_type","") == "Assertion")
    both  = sum(1 for r in rows if r.get("checker_type","") == "Both")
    total_chk = proc + asr + both

    features_in_spec   = data.get("total_features_in_spec", "?")
    features_covered   = len(set(r.get("feature","") for r in rows if r.get("feature","")))

    blocks = [
        ("DV TESTPLAN SUMMARY", None, True, C_SUMMARY_HDR, C_ACCENT),
        (f"Project : {project}", today, False, C_HEADER_BG, None),
        ("Generated by : dv-testplan (S2)", None, False, C_HEADER_BG, None),
        ("", "", False, C_WHITE, None),
        ("TOTAL TESTS", str(total), True, "374151", None),
        ("  Directed", str(directed), False, None, None),
        ("  Random (coverage-driven)", str(random_t), False, None, None),
        ("  Coverpoint-only", str(cov_only), False, None, None),
        ("  Negative / Error Injection", str(neg), False, None, None),
        ("  Corner / Stress", str(stress), False, None, None),
        ("", "", False, C_WHITE, None),
        ("MILESTONE BREAKDOWN", "", True, "374151", None),
        ("  DV-I  (Initial RTL sanity)", str(dvi), False, C_DVI_BG, None),
        ("  DV-C  (Code Complete)", str(dvc), False, C_DVC_BG, None),
        ("  DV-F  (Final RTL sign-off)", str(dvf), False, C_DVF_BG, None),
        ("", "", False, C_WHITE, None),
        ("FUNCTIONAL COVERAGE", "", True, "374151", None),
        ("  Covergroups", str(cgs), False, None, None),
        ("  Coverpoints", str(cps), False, None, None),
        ("  Cross Coverpoints", str(xcps), False, None, None),
        ("", "", False, C_WHITE, None),
        ("CHECKERS", "", True, "374151", None),
        ("  Total Checkers", str(total_chk), False, None, None),
        ("  Procedural", str(proc), False, None, None),
        ("  Assertion-based (SVA)", str(asr), False, None, None),
        ("  Both (Procedural + SVA)", str(both), False, None, None),
        ("", "", False, C_WHITE, None),
        ("FEATURES COVERED", f"{features_covered} / {features_in_spec}", True, "374151", None),
    ]

    for i, (label, value, bold, bg, fg) in enumerate(blocks, start=1):
        ca = ws.cell(row=i, column=1, value=label)
        cb = ws.cell(row=i, column=2, value=value or "")
        for c in (ca, cb):
            c.font = make_font(bold=bold, color=fg or ("FFFFFF" if bg and bg not in (C_WHITE, C_DVI_BG, C_DVC_BG, C_DVF_BG) else "1A1A2E"), size=10)
            c.alignment = Alignment(horizontal="left", vertical="center")
            if bg:
                c.fill = make_fill(bg)
        ws.row_dimensions[i].height = 18 if label else 8


# ── Testplan Sheet ─────────────────────────────────────────────────────────────
def build_testplan_sheet(wb, data: dict, project: str):
    ws = wb.create_sheet("Testplan", 1)
    ws.sheet_view.showGridLines = False
    ws.freeze_panes = "A3"

    # Row 1 — title banner
    ws.merge_cells(start_row=1, start_column=1, end_row=1, end_column=len(COLUMNS))
    title_cell = ws.cell(row=1, column=1,
        value=f"DV Testplan — {project}   |   Generated by dv-testplan (S2)   |   {date.today().isoformat()}")
    title_cell.font  = make_font(bold=True, color="FFFFFF", size=11)
    title_cell.fill  = make_fill(C_HEADER_BG)
    title_cell.alignment = Alignment(horizontal="center", vertical="center")
    ws.row_dimensions[1].height = 22

    # Row 2 — column headers
    for col_idx, (name, width) in enumerate(COLUMNS, start=1):
        cell = ws.cell(row=2, column=col_idx, value=name)
        cell.font      = make_font(bold=True, color="FFFFFF", size=9)
        cell.fill      = make_fill(C_SUMMARY_HDR)
        cell.alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)
        cell.border    = thin_border()
        ws.column_dimensions[get_column_letter(col_idx)].width = width
    ws.row_dimensions[2].height = 28

    rows = data.get("rows", [])
    prev_feature = None

    for row_idx, row in enumerate(rows, start=3):
        feat     = row.get("feature", "")
        subfeat  = row.get("subfeature", "")
        is_neg   = subfeat.startswith("[NEG]")
        is_stress= subfeat.startswith(("[STRESS]", "[CORNER]"))
        ms       = row.get("milestone", "")

        # Row background
        if is_neg:
            row_bg = C_NEG_BG
        elif is_stress:
            row_bg = C_STRESS_BG
        elif ms in MILESTONE_COLORS:
            row_bg = MILESTONE_COLORS[ms]
        elif row_idx % 2 == 0:
            row_bg = C_ALT_BG
        else:
            row_bg = C_WHITE

        values = [
            feat,
            subfeat,
            row.get("brief_description", ""),
            row.get("verification_type", ""),
            row.get("testcase_description", ""),
            row.get("coverpoint_desc", ""),
            row.get("checker_id", ""),
            row.get("checker_type", ""),
            row.get("assertion_code", ""),
            ms,
            row.get("parent_feature", ""),
        ]

        for col_idx, val in enumerate(values, start=1):
            cell = ws.cell(row=row_idx, column=col_idx, value=val or "")
            cell.fill      = make_fill(row_bg)
            cell.border    = thin_border()
            cell.alignment = wrap_align()
            cell.font      = make_font(size=9)

        # Bold the feature cell when it changes
        feat_cell = ws.cell(row=row_idx, column=1)
        if feat != prev_feature:
            feat_cell.font = make_font(bold=True, size=9)
            prev_feature = feat

        # Row height — taller for rows with multi-line content
        max_lines = max(
            len(str(v).split("\n")) for v in values if v
        ) if any(values) else 1
        ws.row_dimensions[row_idx].height = max(18, min(max_lines * 14, 120))

    # Auto-filter on header row
    ws.auto_filter.ref = f"A2:{get_column_letter(len(COLUMNS))}2"


# ── Main ───────────────────────────────────────────────────────────────────────
def main():
    parser = argparse.ArgumentParser(description="Generate DV Testplan Excel")
    parser.add_argument("--data",    required=True, help="Path to testplan_data.json")
    parser.add_argument("--output",  required=True, help="Output .xlsx path")
    parser.add_argument("--project", required=True, help="Project/IP name")
    args = parser.parse_args()

    data_path = Path(args.data)
    if not data_path.exists():
        print(f"ERROR: data file not found: {data_path}")
        sys.exit(1)

    with open(data_path) as f:
        data = json.load(f)

    wb = openpyxl.Workbook()
    # Remove default sheet
    if "Sheet" in wb.sheetnames:
        del wb["Sheet"]

    build_summary_sheet(wb, data, args.project)
    build_testplan_sheet(wb, data, args.project)

    out_path = Path(args.output)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    wb.save(str(out_path))
    print(f"✓ Testplan saved: {out_path}")


if __name__ == "__main__":
    main()
