#!/usr/bin/env python3
"""
write_spec_summary.py — S1 (dv-spec-parse) output writer
Reads a structured spec data JSON and writes:
  - dv_spec_summary.md   (human-readable markdown report)
  - dv_spec_summary.json (machine-readable, downstream-compatible)

Usage:
    python3 write_spec_summary.py \
        --data   /tmp/<project>_spec_data.json \
        --output <output_dir> \
        --project <project_name>

Input JSON schema (written by Claude following SKILL.md Step 3):
{
  "project_name": "apb_uart",
  "source_spec":  "path/to/spec.md",
  "date":         "2026-03-22",
  "block_overview": "...",
  "features": [
    { "id": 1, "name": "...", "description": "...",
      "subfeatures": [{ "id": "1.1", "name": "...", "description": "..." }] }
  ],
  "interfaces": [
    { "name": "...", "type": "...", "protocol": "...", "width": "...", "direction": "...",
      "signals": [{ "name": "...", "direction": "...", "width": "...", "description": "..." }] }
  ],
  "parameters":         [{ "name": "...", "default": "...", "description": "..." }],
  "clock_domains":      [{ "name": "...", "source": "...", "frequency": "...", "affected_logic": "..." }],
  "reset_strategy":     [{ "name": "...", "type": "...", "polarity": "...", "affected_domains": "..." }],
  "operating_modes":    [{ "name": "...", "description": "...", "configuration": "..." }],
  "compliance_standards": [{ "standard": "...", "version": "...", "notes": "..." }],
  "known_constraints":  ["..."],
  "needs_review":       ["..."]
}
"""

import argparse
import json
import sys
from pathlib import Path
from datetime import date as dt_date


# ── Markdown helpers ───────────────────────────────────────────────────────────

def md_table(headers: list, rows: list) -> str:
    col_widths = [len(h) for h in headers]
    for row in rows:
        for i, cell in enumerate(row):
            col_widths[i] = max(col_widths[i], len(str(cell)))
    def fmt_row(r):
        return "| " + " | ".join(str(c).ljust(col_widths[i]) for i, c in enumerate(r)) + " |"
    sep = "| " + " | ".join("-" * w for w in col_widths) + " |"
    lines = [fmt_row(headers), sep] + [fmt_row(r) for r in rows]
    return "\n".join(lines)


def write_md(data: dict, output_dir: Path) -> Path:
    p = data.get("project_name", "unknown")
    src = data.get("source_spec", "")
    today = data.get("date", dt_date.today().isoformat())
    needs_review = data.get("needs_review", [])

    lines = [
        f"# DV Spec Summary — {p}",
        f"Generated by: dv-spec-parse (S1)  ",
        f"Source: `{src}`  ",
        f"Date: {today}",
        "",
        "---",
        "",
        "## 1. Block Overview",
        "",
        data.get("block_overview", "⚠️ NEEDS_REVIEW — block overview not extracted"),
        "",
        "---",
        "",
        "## 2. Feature List",
        "",
    ]

    features = data.get("features", [])
    if features:
        rows = [[f["id"], f["name"], f.get("description","")] for f in features]
        lines.append(md_table(["#", "Feature", "Description"], rows))
    else:
        lines.append("⚠️ NEEDS_REVIEW — no features extracted")
    lines += ["", "---", "", "## 3. Sub-features", ""]

    sub_rows = []
    for f in features:
        for sf in f.get("subfeatures", []):
            sub_rows.append([f["name"], sf.get("id",""), sf["name"], sf.get("description","")])
    if sub_rows:
        lines.append(md_table(["Feature", "ID", "Sub-feature", "Description"], sub_rows))
    else:
        lines.append("⚠️ NEEDS_REVIEW — no sub-features extracted")
    lines += ["", "---", "", "## 4. Interface List", ""]

    interfaces = data.get("interfaces", [])
    if interfaces:
        iface_rows = [[i["name"], i.get("type",""), i.get("protocol",""),
                       i.get("width",""), i.get("direction","")] for i in interfaces]
        lines.append(md_table(["Interface", "Type", "Protocol", "Width", "Direction"], iface_rows))
    else:
        lines.append("⚠️ NEEDS_REVIEW — no interfaces extracted")
    lines += ["", "---", "", "## 5. Signal List", ""]

    sig_rows = []
    for i in interfaces:
        for s in i.get("signals", []):
            sig_rows.append([i["name"], s["name"], s.get("direction",""),
                             s.get("width",""), s.get("description","")])
    if sig_rows:
        lines.append(md_table(["Interface", "Signal", "Direction", "Width", "Description"], sig_rows))
    else:
        lines.append("⚠️ NEEDS_REVIEW — no signals extracted")
    lines += ["", "---", "", "## 6. Parameters", ""]

    params = data.get("parameters", [])
    if params:
        lines.append(md_table(["Parameter", "Default", "Description"],
                               [[p["name"], p.get("default",""), p.get("description","")] for p in params]))
    else:
        lines.append("⚠️ NEEDS_REVIEW — no parameters found")
    lines += ["", "---", "", "## 7. Clock Domains", ""]

    clocks = data.get("clock_domains", [])
    if clocks:
        lines.append(md_table(["Clock", "Source", "Frequency", "Affected Logic"],
                               [[c["name"], c.get("source",""), c.get("frequency",""),
                                 c.get("affected_logic","")] for c in clocks]))
    else:
        lines.append("⚠️ NEEDS_REVIEW — no clock domains extracted")
    lines += ["", "---", "", "## 8. Reset Strategy", ""]

    resets = data.get("reset_strategy", [])
    if resets:
        lines.append(md_table(["Reset", "Type", "Polarity", "Affected Domains"],
                               [[r["name"], r.get("type",""), r.get("polarity",""),
                                 r.get("affected_domains","")] for r in resets]))
    else:
        lines.append("⚠️ NEEDS_REVIEW — no reset strategy found")
    lines += ["", "---", "", "## 9. Operating Modes", ""]

    modes = data.get("operating_modes", [])
    if modes:
        lines.append(md_table(["Mode", "Description", "Configuration"],
                               [[m["name"], m.get("description",""), m.get("configuration","")] for m in modes]))
    else:
        lines.append("⚠️ NEEDS_REVIEW — no operating modes found")
    lines += ["", "---", "", "## 10. Compliance Standards", ""]

    standards = data.get("compliance_standards", [])
    if standards:
        lines.append(md_table(["Standard", "Version", "Notes"],
                               [[s["standard"], s.get("version",""), s.get("notes","")] for s in standards]))
    else:
        lines.append("_No compliance standards specified in spec._")
    lines += ["", "---", "", "## 11. Known Constraints", ""]

    constraints = data.get("known_constraints", [])
    if constraints:
        lines += [f"- {c}" for c in constraints]
    else:
        lines.append("_No explicit constraints stated in spec._")

    if needs_review:
        lines += ["", "---", "", "## ⚠️ Items Requiring Review", ""]
        lines += [f"- {item}" for item in needs_review]

    out_file = output_dir / "dv_spec_summary.md"
    out_file.write_text("\n".join(lines), encoding="utf-8")
    return out_file


def write_json(data: dict, output_dir: Path) -> Path:
    out_file = output_dir / "dv_spec_summary.json"
    # Ensure all required top-level keys exist (downstream compatibility)
    canonical = {
        "project_name":         data.get("project_name", ""),
        "source_spec":          data.get("source_spec", ""),
        "generated_by":         "dv-spec-parse",
        "date":                 data.get("date", dt_date.today().isoformat()),
        "block_overview":       data.get("block_overview", ""),
        "features":             data.get("features", []),
        "interfaces":           data.get("interfaces", []),
        "parameters":           data.get("parameters", []),
        "clock_domains":        data.get("clock_domains", []),
        "reset_strategy":       data.get("reset_strategy", []),
        "operating_modes":      data.get("operating_modes", []),
        "compliance_standards": data.get("compliance_standards", []),
        "known_constraints":    data.get("known_constraints", []),
        "needs_review":         data.get("needs_review", []),
    }
    out_file.write_text(json.dumps(canonical, indent=2), encoding="utf-8")
    return out_file


def print_terminal_summary(data: dict, md_path: Path, json_path: Path):
    features   = data.get("features", [])
    subfeats   = sum(len(f.get("subfeatures",[])) for f in features)
    interfaces = data.get("interfaces", [])
    signals    = sum(len(i.get("signals",[])) for i in interfaces)
    params     = len(data.get("parameters", []))
    clocks     = len(data.get("clock_domains", []))
    modes      = len(data.get("operating_modes", []))
    standards  = len(data.get("compliance_standards", []))
    review     = len(data.get("needs_review", []))
    project    = data.get("project_name","")
    source     = data.get("source_spec","")

    print("=" * 60)
    print("  DV Spec Parse — Complete")
    print(f"  Project  : {project}")
    print(f"  Source   : {source}")
    print(f"  Output   : {md_path.parent}")
    print("-" * 60)
    print("  Extracted:")
    print(f"    Features          : {len(features)}")
    print(f"    Sub-features      : {subfeats}")
    print(f"    Interfaces        : {len(interfaces)}")
    print(f"    Signals           : {signals}")
    print(f"    Parameters        : {params}")
    print(f"    Clock Domains     : {clocks}")
    print(f"    Operating Modes   : {modes}")
    print(f"    Compliance Stds   : {standards}")
    print("-" * 60)
    print(f"  ⚠️  Items needing review : {review}")
    print(f"  Output files:")
    print(f"    → {md_path}")
    print(f"    → {json_path}")
    print("-" * 60)
    print("  Next step: run /dv-testplan to generate the testplan")
    print("=" * 60)


def main():
    parser = argparse.ArgumentParser(description="Write dv-spec-parse output files")
    parser.add_argument("--data",    required=True, help="Path to spec data JSON")
    parser.add_argument("--output",  required=True, help="Output directory")
    parser.add_argument("--project", required=True, help="Project name")
    args = parser.parse_args()

    data_path = Path(args.data)
    if not data_path.exists():
        print(f"ERROR: data file not found: {data_path}")
        sys.exit(1)

    with open(data_path, encoding="utf-8") as f:
        data = json.load(f)

    # Ensure project_name is set
    if not data.get("project_name"):
        data["project_name"] = args.project

    out_dir = Path(args.output)
    out_dir.mkdir(parents=True, exist_ok=True)

    md_path   = write_md(data, out_dir)
    json_path = write_json(data, out_dir)
    print_terminal_summary(data, md_path, json_path)


if __name__ == "__main__":
    main()
